#+layout: post
#+title: 热统 (期末)
#+date: 2022-12-28
#+options: _:nil ^:nil
#+math: true
#+categories: notes
* 统计物理学部分
下半学期的是统计物理学部分. 不过可惜的是, 我的概统没有学得很好,
所以在某些名词 (概统课上) 出现的时候, 我也没法很深入的了解到.
只能说两者之间知道有一个关系, 不过具体是什么关系就说不清楚了.

** Microstates and Marcostates
*** Microstates
微观状态是什么意思?

#+begin_quote
The most *complete* description of a system. 
#+end_quote

这个可能有点难以说明, 但是用概统里面的 $\Omega$
样本空间来理解估计会比较方便. 比如要描述一个物理粒子,
(牛顿的经典力学), 需要 $6$ 个信息: $(q_x, q_y, q_z, p_x, p_y, p_z)$.
同理, 对于一个大系统, 其自然就是 $\Omega = \prod \Omega_i = \Omega_1 \times \cdots \Omega_n$
其部分 (如果是相互之间没有干扰的独立的话) 的简单的并.

注: 如果用相空间来对应这样的一个样本空间的话...
于是就能够定义度量概率的大小了. 及一个 (宏观) 状态对应的可能性,
对应其微观状态在相空间中占的体积:

$$\mathrm{Number\ of\ states} = \frac{\mathrm{Volume\ in\ phase\ space}}{h^3}$$

其中用到了:
+ 微观状态等可能:

  #+begin_quote
  All accessible microstates are equally likely.
  #+end_quote

  (定义样本空间可度量的前提, 由 Ergodic Hypothesis 遍历假设得到. )
+ 在计算相空间中的体积的时候, 以 SHO 简谐振子为例:

  $$E = \frac{1}{2}m v^2 + \frac{1}{2}k x^2 = \frac{p^2}{2m} + \frac{1}{2}k x^2$$
  
  + 连续 (经典) 系统: 因为能量是连续分布的,
    所以对椭圆的相轨道积分即可得到结果.
    
  + 离散 (量子) 系统: 因为能量并不是连续分布的
    $E_n = \frac{\hbar^2}{2m} (\frac{\pi}{L})^2 n^2$. 所以在 $E_n$ 上的体积 $\Delta = \frac{2\pi}{\omega} (E_{n+1} - E_{n})$

Allowed Microstates (允态, 我这么叫):

#+begin_quote
We consider every microstate an allowed microstate
if it is consistent with all external constraints.
#+end_quote

尽管有点像是 =microstates.select {|state| state.allowed? }=
这样的操作. 但是换一种想法, 通过限制概率空间 $\Omega|_A$,
于是就能够得到一个允态的一个概念. 直观的例子就是在空间中有一堆粒子,
但是被隔板限制在一个区域. 或者一个更加实际的例子就是在一个系统里面,
在不同能级的粒子数量并非任意分布, 比如在某个能量上只能有 $K$ 个之类的.

*** Macrostates
目前的直观感觉就是, Macrostates, 宏观状态就像是概统里面的统计量.
或者说, 有点像是一个信息被压缩了之后观察到的一个样本空间.

热力学中找的统计量 $S$ 熵满足广延量性质: $S = S_1 + S_2$,
而微观状态数满足 $\Omega = \Omega_1 \times \Omega_2$,
所以通过对数函数将其联系在一起:

$$S = k \mathrm{ln}\Omega$$

通过引入一个配分函数 (物理含义是所有的能量状态的和,
其中的 "所有能量" 指的是一个粒子可能的能量取值的所有可能,
或者可以用概统的 (充分? ) 统计量来理解):

$$Z(\beta) = \sum f_{Z}|_\beta(\varepsilon_i)$$

而, 并不是所有的能量态都能够被描述, 所以引入态密度 DOS,
即在 $\varepsilon$ 附近的能级的数量 $\mathrm{d}n = \omega(\varepsilon) \mathrm{d}\varepsilon$.
比如钠黄双线的就可以把 $n = 2$, 然后用单线能量来代替.
(有一种简并能级的感觉了, 如果是离散的条件下的话)

$$Z(\beta) = \int_0^\infty \omega(\varepsilon) f_Z|_\beta(\varepsilon) \mathrm{d}\varepsilon = \sum \omega_i f_Z|_\beta(\varepsilon_i)$$

(注: 这里的都是计算单个粒子的一个配分函数的操作. )

通过配分函数可以来得到热力学的各种信息:
+ $U = N\frac{\partial \mathrm{ln} Z}{\partial \beta} \Rightarrow C_V = \frac{\partial U}{\partial T}$

  ($\beta$ 为与 $T$ 有关的量)
+ $F = U - T S = - N k_B \mathrm{ln} Z \Rightarrow S = -(\frac{\partial F}{\partial T})_{V, N}$

#+begin_quote
一些例题:
+ $N$ localised and weakly interacting particles having:

  $$Z = 2 \cosh (\mu B / k_B T)$$

  因为是 localised, 所以 $Z_{\mathrm{total}} = Z^N$,
  于是可以计算得到:
  + $F = - k_B T \mathrm{ln} Z_{\mathrm{total}} = -N k_B T (\mathrm{ln}2\cosh(\mu B / k_B T))$
  + $E = -\frac{\partial \mathrm{ln}Z}{\partial \beta} = - N \mu B \tanh(\mu B / k_B T)$
+ 若上面的结果变成了 not localised 且 indistinguishable.

  $$Z_{\mathrm{total}} = \frac{Z^N}{N!}$$

  于是可以计算得到...
#+end_quote

*** DOS
在计算态密度的时候, 一般是将 $\varepsilon$ 和一个均匀分布的,
或者是概率分布已知的量做一一映射, 然后计算态密度.

比如已知 $X$ 的分布为 $\omega(X)$, 那么

$$\omega(\varepsilon) \mathrm{d}\varepsilon = \omega(X) \mathrm{d}X \Rightarrow \omega(\varepsilon) = \omega(\varepsilon) \frac{\mathrm{d}X}{\mathrm{d}\omega}$$

其中在计算 $\omega(X)$ 的时候, 一般采用的方法如下:
+ 首先知道单位:

  以自由电子气在 $1$ 维势井中为例: $\Delta = (\Delta k_x) = \frac{\pi}{a_x}$,
  其中 $a_x$ 为势井的宽度, $k_x$ 为势井中的波矢.
  拓展到 $n$ 维应该同理.
+ 然后计算在 $k$ 附近的简并度, 即在 $\mathrm{d}k$ 的一个临域内,
  有多少的态:

  $$\omega(\varepsilon)\mathrm{d}\varepsilon = \mathrm{d}\omega = f(k)\mathrm{d}k / \Delta$$

#+begin_quote
+ 自由电子气
  + 2 维情况: $\Delta = \frac{\pi^2}{a^2} = \frac{\pi^2}{A}$

    $$\omega(k) \mathrm{d}k = \frac{1}{4} 2 \pi k \mathrm{d}k / \Delta$$

  + 其他就同理了. 
+ 光子气体
#+end_quote

#+begin_quote
一些例题:
+ In the lectures, we saw that, for a three dimensional gas of Fermions,
  the average energy of a particle is $\frac{3}{5}\varepsilon_F$ at $T = 0K$.
  Revisit the derivation of this (lecture notes) and show that, for
  a two dimensional gas of electrons (for which the density of states
  is independent of energy), the average energy becomes $\frac{1}{2}\varepsilon_F$.

  + $N = \int \omega(\varepsilon)\mathrm{d}\varepsilon = C_0 \varepsilon_F$
  + $E = \int \varepsilon \omega(\varepsilon) \mathrm{d}\varepsilon = C_0 \frac{\varepsilon_F^2}{2}$

  于是 $\bar{E} = \frac{E}{N} = \frac{\varepsilon_F}{2}$
#+end_quote

** Distributions
实际上这三个分布应该是类似的. 但是具体还是有点不同的.
主要的做法如下: ([[https://zhuanlan.zhihu.com/p/103767620][参考]])
1. 设立配分函数 $Z$

   需要区分的是, $Z$ 是对整个系统还是单个粒子的:
   + 单个粒子: $Z = \int_0^\infty \omega(\varepsilon) \mathrm{d}\varepsilon$
   + 对于多个粒子:
     + 如果是相互之间可以区分的: $Z_{\mathrm{total}} = Z^n$
     + 如果是相互之间不能区分的: $Z_{\mathrm{total}} = \frac{Z^n}{n!}$
2. 通过配分函数得到分布: $n_j^* = N P(\varepsilon_j)$,
   其中, $P(\varepsilon_j) = \frac{1}{Z} e^{\beta \varepsilon}$
   为在能量为 $\varepsilon_j$ 态上的可能性.

   于是对于 $n$ 个粒子 (相互独立) 同时处在 $\varepsilon$ 态,
   其可能性就是 $P(n) = \frac{1}{Z} e^{n \beta (\varepsilon - \mu)}$. 

   注: $\mu$ 为外场的势能. 或者也能够叫化学能,
   因为 (大多) 是用来限制粒子运动的一个能. 

当然, 也能够用另外的一种方法来做: 通过计算 $\Omega$,
然后利用拉格朗日乘子法解 $\Omega$ 最大的情况:

$$\sum [\mathrm{ln} \Omega + a \sum n_i + b \sum \varepsilon_i] = 0$$

*** Maxwell-Boltzman Distributions
$$n_j^* = N\frac{e^{-\varepsilon_j / (k_B T)}}{Z}$$

其对应的配分函数为:

$$Z_{MB} = \sum \omega_i e^{\beta \varepsilon_j}$$

其中 $\beta = -\frac{1}{k_B T}$.

#+begin_quote
理想气体的一个例子:

对于一个粒子 (因为理想气体里面的每个粒子是独立的):

$$Z_{\mathrm{single}} = \int_0^\infty \omega(\varepsilon) e^{\beta \varepsilon}\mathrm{d}\varepsilon$$

其中 $\omega(\varepsilon)$ 在 3 维情况下为: $\frac{V}{4\pi^2} (\frac{2m}{\hbar^2})^{3/2} \varepsilon^{1/2}$

于是积分得到: $Z_{\mathrm{single}} = V (\frac{2\pi m k_B T}{h^2})^{3/2} = V (\frac{2 \pi m}{-\beta h^2})^{3/2}$

拓展到多个粒子的系统: $Z = Z_{\mathrm{single}}^N$,
于是可以计算得到能量和其他的东西:
+ $E = \frac{\partial}{\partial \beta} \mathrm{ln}Z = -\frac{3 N}{2}\frac{1}{\beta} = \frac{3}{2} N k_B T$
+ $C_V = \frac{\partial E}{\partial T} = \frac{3}{2}N k_B$
+ $F = - k_B T \mathrm{ln}Z = -k_B T [N \mathrm{ln}V - \mathrm{ln}(N!) + \frac{3N}{2} \mathrm{ln}(\frac{2\pi m k_B T}{h^2})]$
+ $S = -(\frac{\partial F}{\partial T})_{N, T} = N k_B [\mathrm{ln} V - \mathrm{ln}N + \frac{3}{2} \mathrm{ln} T + \frac{3}{2} \mathrm{ln}(\frac{2 m \pi k_B}{h^2}) + 1 + \frac{3}{2}]$
+ $P = -(\frac{\partial F}{\partial V})_{T, N} \Rightarrow P V = \frac{2}{3} E$
+ 以及速度分布:

  $$n = \frac{N}{Z} \omega(\varepsilon) e^{\beta \varepsilon}\
  \Rightarrow n(v) \mathrm{d}v = \frac{N}{Z} \omega(v) e^{\beta \varepsilon(v)} \mathrm{d}v$$

  然后经过复杂的计算可以得到速度分布.
  其中用到一个 $\int n(v) \mathrm{d} v = N$
#+end_quote

并且单个粒子的配分函数中的能量并不一定只能是平动动能,
还能够加上转动, 振动等.

*** Fermi-Dirac Distributions
费米子满足可区分: $\psi(2, 1) = - \psi(1, 2)$,
于是也满足不相容: $\psi(1, 1) = 0$.

所以对于费米子, 一个粒子在 $\varepsilon$ 态,
可能的情况只能是 1 个或者 0 个. 

$$n_j^* = E n = 0 P(0) + 1 P(1) = \frac{1}{Z} e^{\beta (\varepsilon - \mu)}$$

其中 $Z = \sum_{n = 0, 1} e^{n \beta (\varepsilon - \mu)} = 1 + e^{\beta (\varepsilon - \mu)}$. 

于是得到分布: $n_{FD} = \frac{1}{1 + e^{-\beta (\varepsilon - \mu)}}$.

其中, $\mu = \varepsilon_F [1 - \frac{\pi^2}{12} (\frac{T}{T_F})^2]$. 可以通过拉格朗日乘子法计算出来.

对于一个气体:

$$E = \int_0^\infty \varepsilon \omega(\varepsilon) \mathrm{d}\varepsilon = \int_0^\varepsilon_F$$

$$N = \int_0^\infty \omega(\varepsilon) \mathrm{d}\varepsilon = \int_0^\varepsilon_F$$

$$\frac{E}{N} = \frac{3}{5} \varepsilon_F$$

+ $P = -\frac{\partial E}{\partial V} = - \frac{3}{5} N \frac{\partial \varepsilon_F}{\partial V}$

  然后利用 $\varepsilon_F = \frac{\hbar^2}{2m}(3\pi^2 n)^{2/3}$,
  以及 $n = N / V$, 可以得到: $P = \frac{2}{5}n \varepsilon_F$. 

#+begin_quote
一些例题:
+ Show that for Fermions, the probability that a level $\delta$
  above the Fermi energy is occupied is equal to the probability
  that a level $\delta$ below the Fermi energy is unoccupied.

  即证明在费米分布中: $f(\mu + \delta) = 1 - f(\mu - \delta)$.
  带入 $f(\varepsilon)$ 即可.
#+end_quote
*** Bose-Einstein Distributions
玻色子不可区分, 所以 $\psi(1, 2) = \psi(2, 1)$,
在一个态里面可能有多个粒子:

$$Z = \sum_{n = 0}^{\cdots} e^{n \beta (\varepsilon - \mu)}$$

在 $T \rightarrow 0$ 或者 $\varepsilon \gg \mu$ 的时候, 有 $Z = \frac{1}{1 - e^{\beta (\varepsilon - \mu)}}$.

令 $x = \beta (\varepsilon - \mu)$, 于是有:

$$n_{BE} = \frac{1}{Z} \frac{\partial Z}{\partial x} = \frac{1}{e^{-\beta (\varepsilon - \mu)} - 1}$$

#+begin_quote
Planck Distributions

首先对 $n = \frac{N}{V}$ 和 $u = \frac{U}{V}$ 进行一个积分:
+ $n = \frac{1}{V} \int \omega(\varepsilon) n_{BE} \mathrm{d}\varepsilon$

  其中令外场为零 $\mu = 0$, $\omega = 2V \frac{\varepsilon^2}{2\pi^2 \hbar^3 c^3}$,
  然后积分变为 $n = c_0 \int \varepsilon^2 \frac{1}{e^{\varepsilon / k_B T} - 1}\mathrm{d}\varepsilon$,
  其中 $c_0$ 为常数.
+ $u = \frac{1}{V} \int \omega(\varepsilon) \varepsilon n_{BE} \mathrm{d}\varepsilon$

上面两个的积分的操作都差不多,
最终需要处理的就是一个 $I(p) = \int_0^\infty \frac{x^{p-1}}{e^x - 1}\mathrm{d}x$ 的积分.

直接上结论:
+ $u = \frac{\pi^2 k_B^4}{15 (\hbar c)^3} T^4$

从而可以计算得到: $u_\omega = \frac{\hbar}{\pi^2 c^3} \frac{\omega^3}{e^{\frac{\hbar \omega}{k_B T}} - 1}$.
+ $\omega \rightarrow 0: u_\omega \approx \frac{k_B T}{\pi^2 c^3} \omega^2$
  也就是 Rayleigh-Jean's Law
+ $\omega \rightarrow \infty: u_\omega \approx \frac{\hbar}{\pi^2 c^3} \omega^3 e^{-\frac{\hbar \omega}{k_B T}}$
  也就是 Wien's Law
#+end_quote

** Ensemble Theory
前文中的思考方式都是从一个微观的粒子出发,
比如说单个粒子可能有某某性质之类的.

现在用一团粒子作为一个粒子来看待,
找一个统计量作为这一团粒子的信息来做.

*** Liouville's Theorem
$$\frac{\mathrm{d} \rho}{\mathrm{d} t} = \frac{\partial \rho}{\partial t} + [H, \rho] = 0$$

即在相空间的 (局域) 密度不变.

#+begin_quote
Namely, the "local" density of representative points,
as viewed by an observer moving with a representative point,
stays constant in time in phase space for equilibrium.
#+end_quote

于是可以用平均值来去表示一个物理量.
