#+layout: post
#+title: 电动力学
#+date: 2023-05-04
#+options: _:nil ^:nil
#+math: true
#+categories: notes
* 矢量分析
+ 场: /物理量在空间的分布/

  Note: 经典场, 可以认为是一个场算符在空间的平均值
+ 矢量的运算
  + 数乘
  + 标量积 \(\boldsymbol{A} \cdot \boldsymbol{B} = A_i B_j \delta_{ij}\)
  + 矢量积 \(\boldsymbol{A} \times \boldsymbol{B} = A_i B_j \varepsilon_{ijk} \boldsymbol{e}_k\)
  + 混合积 \((\boldsymbol{A} \times \boldsymbol{B}) \cdot \boldsymbol{C}\) 奇偶置换改变符号
  + 并矢 \(\boldsymbol{A} \boldsymbol{B} = A_i B_j \boldsymbol{e}_i \boldsymbol{e}_j\)

    Note: 并矢是张量但是张量并不是并矢.

    (注: 因为目前接触的还都是各向同性介质, 所以就不写了. )
+ \(\nabla = \frac{\partial}{\partial q_i} \boldsymbol{e}_i\)
  + 积分和微分形式的变换
    + \(\boldsymbol{\nabla} \cdot \boldsymbol{f} = \lim_{V \rightarrow 0} \frac{\oint \boldsymbol{f} \cdot \boldsymbol{S}}{V}\)
    + \(\boldsymbol{\nabla} \times \boldsymbol{f} = \lim_{S \rightarrow 0} \frac{\oint \boldsymbol{f} \times \boldsymbol{l}}{S}\)
  + 符号的化简与计算

    Note: 满足矢量性和算符性

    Note: 一些结果和公式
    + \(\nabla r = \frac{\boldsymbol{r}}{r}\)
    + \(\nabla (\frac{\boldsymbol{r}}{r^3}) = 4 \pi \delta(\boldsymbol{r})\)
    + \(\nabla (\boldsymbol{A} \cdot \boldsymbol{B}) = \boldsymbol{A} \times (\nabla \times \boldsymbol{B}) + (\boldsymbol{A} \cdot \nabla) \boldsymbol{B} + \cdots\)
+ 不同坐标系的矢量运算
  + 拉梅系数 \(h_i = \sqrt{\partial_i x + \partial_j y + \partial_k z}\)
* 电磁现象的普遍规律
** 电磁介质
*** 电介质
+ 电极化强度 \(\boldsymbol{P} = \frac{\sum \boldsymbol{p}_i}{\Delta V} = \boldsymbol{D} - \varepsilon_0 \boldsymbol{E}\),
  在 _各向同性_ 介质中有 \(\boldsymbol{P} = \chi_e \varepsilon_0 \boldsymbol{E}\) 以及 \(\boldsymbol{D} = \varepsilon \boldsymbol{E}\),
  于是可以有 \(\chi_e = \frac{\epsilon - \epsilon_0}{\varepsilon_0}, \boldsymbol{D} = \frac{\varepsilon \boldsymbol{P}}{\varepsilon - \varepsilon_0}\). 
+ 极化面电荷 \(\sigma_P = - \boldsymbol{e}_n \cdot (\boldsymbol{P}_2 - \boldsymbol{P}_1)\)
+ 极化体电荷 \(\rho_P = \varepsilon_0 \nabla \cdot \boldsymbol{E} - \rho_f = - \nabla \cdot \boldsymbol{P}\)

*** 恒稳电流
+ 电流和电场 \(\boldsymbol{J} = \sigma \boldsymbol{E}\)
+ 电荷守恒 \(\partial_t \rho + \nabla \cdot \boldsymbol{J} = 0\)
  
*** 磁介质
+ \(\boldsymbol{m} = I \Delta \boldsymbol{S}\)
+ \(\boldsymbol{M} = \frac{\sum \boldsymbol{m}_i}{\Delta V} = \frac{\boldsymbol{B}}{\mu_0} - \boldsymbol{H}\),
  在各向同性的介质中有 \(\boldsymbol{M} = \chi_M \boldsymbol{H}, \boldsymbol{B} = \mu \boldsymbol{H}\). 
+ 磁化电流 \(\boldsymbol{J}_M = \boldsymbol{J} - \boldsymbol{J}_f = \nabla \times \boldsymbol{B} - \boldsymbol{J}_f\)
+ 磁化面电流 \(\boldsymbol{e}_r = \boldsymbol{e}_r \times (\boldsymbol{H}_2 - \boldsymbol{H}_1)\)
  
** 麦克斯韦方程组
\[\left\{\begin{matrix}\nabla \times \boldsymbol{E} & = & - \frac{\partial \boldsymbol{B}}{\partial t}\\\\\nabla \times \boldsymbol{H} & = & \boldsymbol{J} + \frac{\partial \boldsymbol{D}}{\partial t}\\\\\nabla \cdot \boldsymbol{D} & = & \rho\\\\\nabla \cdot \boldsymbol{B} & = & 0\end{matrix}\right.\]

微分形式在连续介质内部可用,
但是在不连续界面上, 物理量产生了跃变,
微分形式并不适用, 需要改用积分形式:

\[\left\{\begin{matrix}\oint \boldsymbol{E} \cdot \mathrm{d} \boldsymbol{l} & = & \frac{\partial}{\partial t} \int \boldsymbol{B} \cdot \mathrm{d} \boldsymbol{S}\\\\\oint \boldsymbol{H} \cdot \mathrm{d} \boldsymbol{l} & = & I + \frac{\partial}{\partial t} \int \boldsymbol{D} \cdot \mathrm{d} \boldsymbol{S}\\\\\oint \boldsymbol{D} \cdot \mathrm{d} \boldsymbol{S} & = & \int \rho \mathrm{d} V\\\\\oint \boldsymbol{B} \cdot \mathrm{d} \boldsymbol{S} & = & 0\end{matrix}\right.\]

#+begin_quote
已知轴对称磁场中的 \(\boldsymbol{B}_z\), 如何计算 \(\boldsymbol{B}_{\rho}\):
利用 \(\nabla \cdot \boldsymbol{B} = 0\) 以及对称性来计算. 
#+end_quote

可以得到边界条件:

\[\left\{\begin{matrix}\boldsymbol{e}_n \times (\boldsymbol{E}_2 - \boldsymbol{E}_1) & = & 0\\\\\boldsymbol{e}_n \times (\boldsymbol{H}_2 - \boldsymbol{H}_1) & = & \boldsymbol{\alpha}\\\\\boldsymbol{e}_n \cdot (\boldsymbol{D}_2 - \boldsymbol{D}_1) & = & \sigma\\\\\boldsymbol{e}_n \cdot (\boldsymbol{B}_2 - \boldsymbol{B}_1) & = & 0\end{matrix}\right.\]

#+begin_quote
利用边界条件来计算方程的时候需要用到的东西:
+ 电势: \(\varepsilon_1 \partial_n \varphi_1 = \varepsilon_2 \partial_n \varphi_2\)
+ 磁标势: \(\mu_1 \partial_n \varphi_{m1} = \mu_2 \partial_n \varphi_{m2}\)
#+end_quote

** 电磁场的能量
+ \(\boldsymbol{S} = \frac{1}{\mu_0} \boldsymbol{E} \times \boldsymbol{B}\)
+ \(w = \frac{1}{2} (\boldsymbol{E} \cdot \boldsymbol{D} + \boldsymbol{H} \cdot \boldsymbol{B}) = \frac{1}{2} (\varepsilon \boldsymbol{E}^2 + \mu \boldsymbol{H}^2)\)

  (后者仅在各向同性的介质中成立; 整个式子仅在线性介质中成立. )
+ 能量在导体中的传播 \(\boldsymbol{J} = \sigma \boldsymbol{E}\), 以及 \(\nabla \times \boldsymbol{H} = \boldsymbol{J}\).   
  
#+begin_quote
计算能量
#+end_quote

* 静电场
** 分离变量法求解电场
对于拉普拉斯方程: 

\[\nabla^2 \varphi = 0\]

理论上对于轴对称情况, 其解为 (可以参考数学物理方程):

\[\varphi = \sum_n (a_n r^n + \frac{b_n}{r^{n+1}}) P_n(\cos \theta)\]

求解步骤:
+ 装模作样地写出方程然后直接写出通解形式 (甚至最后连装都可以不装了)
+ 判断球内还是球外还是球壳内 (通过自然边界条件来减少未定系数):
  + 球内: \(b_n \rightarrow 0\)
  + 球外: \(a_n \rightarrow 0\)
  + 球壳内没法减少, 只能通过两个边界条件去进行展开
+ 代入边界条件计算系数:
  + 通常只需要代入
    + \(P_0(\cos \theta) = 1\),
    + \(P_1(\cos \theta) = \cos \theta\),
    + \(P_2(\cos \theta) = \frac{1}{2} (3 \cos^2 \theta - 1)\)
  + 如果遇到不太能简单代入的, 就需要通过 Legendre 展开来计算

#+begin_quote
均匀外场的介质球的电势解:

\[\left\{\begin{matrix} \varphi & = & - E_0 R \cos \theta + \frac{\varepsilon - \varepsilon_0}{\varepsilon + 2 \varepsilon_0} \frac{E_0 R_0^3 \cos \theta}{R^2} \\\\ \varphi_2 & = & - \frac{3 \varepsilon_0}{\varepsilon + 2 \varepsilon_0} E_0 R \cos \theta\end{matrix}\right.\]
#+end_quote

#+begin_quote
电偶极子的电势解: 把结果拆成 \(\nabla^2 \varphi = 0\) 以及 \(\varphi = \frac{\boldsymbol{p} \cdot \boldsymbol{r}}{4 \pi \varepsilon_0 r^3}\),
然后代入方程的边界条件去求解. 
#+end_quote

** 电像法
电像法不是空间延拓, 而是通过引入一个虚假电荷来计算原空间的大小.

+ 平面镜像

  正如其名 \(r' = - r, q' = - q\)
+ 球镜像

  可以通过相似三角形来得到 \(r' = \frac{R_0^2}{r}\)

  (Note: 可以用最近和最远的两个部分作为条件来去求解)
** 格林函数


** 电多极矩展开
\[\varphi = \frac{1}{4 \pi \varepsilon_{0}} (\frac{Q}{r} - \boldsymbol{p} \cdot \nabla \frac{1}{r} + \frac{1}{6} \mathcal{D} : \nabla \nabla \frac{1}{R} + \cdots)\]

+ 电偶极矩 \(\boldsymbol{p} = q \boldsymbol{l}\)

  其势 \(\varphi = \frac{\boldsymbol{p} \cdot \boldsymbol{R}}{4 \pi \varepsilon_0 R^3}\), 可以用这个来猜特解. 

  其对应的能量为 \(- \boldsymbol{p} \cdot \boldsymbol{E}\)
+ 电四极矩 \(\mathcal{D}_{ij} = \int_V (3 x_i x_j - r^2 \mathcal{I}) \rho(r) \mathrm{d}V\)

  其对应的能量为 \(- \frac{1}{6} \mathcal{D} : \nabla \boldsymbol{E}\)
+ 电多极矩
* 静磁场
** 矢势
\[\nabla \times \boldsymbol{A} = \boldsymbol{B}\]

如何通过 \(\boldsymbol{B}\) 来求解 \(\boldsymbol{A}\):
+ 矢势和规范条件: \(\boldsymbol{A} + \nabla \psi \Leftrightarrow \boldsymbol{A} \Rightarrow \nabla \cdot \boldsymbol{A} = 0\)
+ \(\boldsymbol{B} = \nabla \times \boldsymbol{A}\) 一般可以通过对称性来减少计算量
+ 或者可以通过 \(\boldsymbol{A} = \frac{\mu_0}{4\pi} \oint \frac{I \mathrm{d}\boldsymbol{l}}{r}\) 来计算矢势
** 磁标势
在 \(\oint \boldsymbol{H} \cdot \mathrm{d} \boldsymbol{l} = 0\), 可以认为其为 \(\boldsymbol{H} = - \nabla \varphi\). 

使用磁标势来求解问题的方法和电势的方法类似.

#+begin_quote
均匀外场下的铁球的磁标势解:

\[\left\{\begin{matrix} \varphi_1 & = & \frac{R_0^3}{3} \frac{\boldsymbol{M}_0 \cdot \boldsymbol{R}}{R^3} \\\\ \varphi_2 & = & \frac{1}{3} \boldsymbol{M}_0 \cdot \boldsymbol{R}\end{matrix}\right.\]
#+end_quote

** 磁多极矩
磁偶极子的势 \(\varphi = \frac{\boldsymbol{m} \cdot \boldsymbol{R}}{4 \pi R^3}\)

** A-B 效应
通过双缝干涉的装置和螺线管来说明 \(\boldsymbol{B}\) 不是唯一描述磁场的物理量,
还需要 \(\boldsymbol{A}\) 的描述. 

** 超导
+ 两类超导体:
  + 第一类超导体: 存在临界磁场 \(H_C [1 - (\frac{T_1}{T_2})^2], T \leq T_C\)
  + 第二类超导体: 存在下临界磁场和上临界磁场, 于是有超导态, 混合态, 正常态.

    有皮纳得局域近似: \(J_s = - \frac{e n s^2}{m^{*}} A\)
+ 伦敦唯象理论
  + 伦敦第一方程 \(\boldsymbol{J} = \boldsymbol{J}_{normal} + \boldsymbol{J}_{super-conduct}\)
    
    其中, \(\boldsymbol{J}_{normal} = \sigma \boldsymbol{E}\), \(\boldsymbol{J}_{super-conduct} = \rho_s \boldsymbol{v} = n_s e \boldsymbol{v}, \partial_t \boldsymbol{J} = \alpha \boldsymbol{E}\)
  + 伦敦第二方程 \(\partial_t \boldsymbol{J} = - \alpha \boldsymbol{B} \Rightarrow \boldsymbol{B} = B_0 e^{-z/\lambda l} \boldsymbol{e}_l\). 

#+begin_quote
超导球应当有 \(\boldsymbol{B}_r = \partial_r \varphi_m = 0\) 可以用来作为边界条件来计算结果. 
#+end_quote

* 后记
要是数学物理方程的考试卷这样就好了, 什么叫做原题啊 (摊手)~

+指在电动力学的考卷里面看到了数学物理方程的原题, 但是因为知道电动力学的结论所以不用死算+

终于, 期中考试这个可以结束了, 接下来欠的一堆债要还了. 
