#+title: 吃一顿独立游戏的大餐
#+date: 2023-11-10
#+layout: post
#+options: _:nil ^:nil
#+categories: misc
* About
在巴黎进行 iGEM 的一个比赛, 机缘巧合, 恰好碰上巴黎游戏周 (Paris Game Week),
又恰好在一个昏暗的夜晚, 在走出展馆的一刻, 恰好遇见了一位独立游戏方面的从业者.

于是在 Judge Session 之后稍稍松了一口气时, 我幸运地得以和大佬约了一餐,
(不是说有什么巴菲特的午餐么? 我觉得这餐估计也该配得上有如此的地位,
虽然作为学生穷鬼, 我只能尴尬的提出一个 AA).

这里记录一些我对大佬分享的一些零星的记忆, 要是忘了太多了,
大概是因为最后打游戏太高兴, 结果忘光了吧, 害.

* 横井军平: 枯れた技術の水平思考
翻译过来就是枯萎技术的水平思考.

这句话应该需要从两个部分来看待, 一个是前一半的枯萎技术, 另一个则是水平思考.
虽然前者比较夺人眼目, 但是比较重要的部分应该是集中在后面的水平思考.

** 水平思考
与之对比的是纵向思考: 比如芯片从 M1 到了 M3 之类的, 在数值上的变化的一个说明力,
但是在用户体验上呢? 可能并没有那么明显的一个变化. 类似于一个技术有进步,
但是这个进步带来的用户体验并不一定是非常显著的.

#+begin_html
<details><summary>一些小小的注记</summary>
#+end_html
并不是说技术的进步没有用处, 比如游玩的时候, 一点点的延时, 比如音游玩家之类的,
估计会比较敏感, 而技术的提升和完善可能可以减缓这个延时的感觉.
又或者说之前有一个用虚幻 5 引擎制作的一个游戏宣传, 几乎和真实拍摄一样,
让人根本分不清. 

但是除非过于离谱, 一般这样的提升可能是比较难以察觉的
(除非是类似于用过了那种非常快的电脑, 然后回过头来去用很慢的电脑去跑);
并且虽然画面固然重要, 比如因为现实中不可能使用枪械或者是很难真的自己开飞机/卡车,
所以对于对于这样的模拟类型的游戏, 真实性可能是非常有必要的.

但是从另外一个角度来看, 游戏可能就是在追求一种不真实的感觉,
那种所谓元宇宙模拟一切的视角, 其实某种程度上来说是非常愚蠢的事情:
我们为什么要去模拟一个啥都和现实一样的东西? 游戏之所以吸引人,
不就是因为它不真实, 它去掉了一些本来应该存在的东西,
把焦点集中在一个最有趣的部分.

以 FPS 为例, 我们可能不需要考虑如何瞄准, 毕竟视野中心就有一个准星,
也不需要考虑如何换手持械更不需要考虑如何换弹等等,
这些现实中复杂的操作都被简化为了一个简单的按键: 比如鼠标单击, 比如 R 键换弹.
(不过如果是更加硬核一点的游戏, 可能也会把这种考虑进去吧?
不过也许这个时候, 游戏的核心体验就变成了对枪械的精确模拟,
而吸引的用户可能就不是射击游戏爱好者, 而是军迷了).

再有一个例子, 是落日间有一个 "元宇宙的厕所会堵吗" 的一个视频,
比如说在游戏场景中的厕所需要设计成什么样的一个形式, 它们需要如何进行设计?
真的有必要去完美复现现实吗? 

(注: 具体的可能还得去看原视频, 我在飞机上也没法找到出处考证了)

这种做法的感觉让我有一种在搞物理的感觉,
有点类似于搞一个简单的模型, 不必所有细节都包含, 但是要有核心的重点.

然后还有一个反其道而行之的另外一个做法: 通过一些真实性来把玩家拉入游戏世界中.
一个例子就是塞尔达里面的木板被设计为可以破坏的,
或者是给松达建的指路牌是可以做得歪歪扭扭的.
这有点像是稍微小小地模糊了一些游戏和现实的边界 -- 否则就会像是一些粪作一样被喷:
这个平台怎么跳不上去? 这个怎么会有空气墙? 这建模也太假了! 这操作太反人类了!

玩家通过用现实在虚拟游戏中进行映射来寻找一种沉浸感, 假如完全的非真实,
那么玩家可能就只是一个旁观者而非参与者了.
#+begin_html
</details>
#+end_html

而水平思考 (或者说横向思考), 则会有一种类似于跨界的感觉.
比如横井军平做的 "爱情检测仪": 其原理其实可以说是一个电阻测量仪
(要真说有啥科学依据, 手心会出汗算么? ), 但是拿来作为一个检测仪,
还是 "爱情" 检测, 则就比较神奇了.

又比如应用在洗手台的红外测距 (或者说, 红外感应), 这绝对不是啥黑科技,
但是如果用在博物馆的展台前, 比如说在地上贴几张不同距离的贴纸,
然后根据人站在不同贴纸上面, 会显示不同的说明文字 (比如不同语种的说明).
在一般用户的体验上, 就好像是这个贴纸有什么魔力一样, 可以自动感应.

这些技术可能并不是一些新的尖端科技, 甚至很可能是一些十几年前就已经成熟了,
甚至快要成为所谓 "夕阳" 技术的东西了, 但是应用在一些意想不到的领域,
比如说游戏中, 就会让人有一种哇塞的感觉.

#+begin_html
<details><summary>和 iGEM 以及其他的类似的地方</summary>
#+end_html
其实我真觉得像 iGEM 这种工程应用 (或者说, 产品开发? ) 的选题也非常需要这样的想法.
比如我见到的把 3D 打印技术应用到培养基制作的, 或者是让工程菌组成结构进行生物制造的,
再或者是往牛乳头上抹工程菌减少牛奶浪费的.

以今年 Willim-Marry 队伍做的 3D 打印培养基为例, 可能这个技术并不是非常先进,
甚至因为他们能做的只有说是固态的,
在实用价值上 (至少据搞生物的师兄说) 可以是没啥意义的.
但是我认为其意义在于引入了这个技术到 iGEM 合成生物学的领域里面,
解决了一定的痛点: 抹培养基挺麻烦, 并且引入 3D 打印技术, 还能够制成任意形式的培养基.
至于未来能否把这个做到别的物态, 那个估计就是另外一回事了.
#+begin_html
</details>
#+end_html

** 用户体验
那么这个 "哇塞" 的感觉就是一种用户的体验.

独立游戏和 3A 大作的一个区别可能就是在用户体验上的取舍考量.
大厂或者 3A 大作为了需要回本, 需要尽可能多地去考虑给予更多不同方面的用户体验,
或者说为了吸引更多用户, 需要啥都要有. 于是这就导致了啥都有,
但是混在一起有些被稀释了, 或者说, 有点平庸.

而好的独立游戏, 一般的定位就是着重去提供一种的比较强烈的, 有自己独特风格的体验.
或者说, 就是为了这个体验, 才去设计这个游戏. 比如说在弹幕射击类的游戏,
可能是一种躲避子弹 (或者是擦弹的快乐, +当然, 万一有人像我一样喜欢接子弹... bushi+)
然后享受挑战的快乐, 或者是享受那种华丽炫酷的画面; 又或者是类似于空洞骑士,
那种想要挑战自己 +受苦+ 的体验.

这种体验就是能够把用户持续拉回游戏的一个持续动力, 而如果只有比较平庸的一个体验,
那么用户的留存就是一个比较头疼的问题了.

#+begin_html
<details><summary>游戏和其他形式的艺术的不同用户体验</summary>
#+end_html
一个直观的表现就是, 你可以从一个用户在说什么来看出他/她在玩游戏还是在做其他的什么:
如果他/她在说: "啊, 我死了", 那么很可能他/她在玩游戏. 你不会看到一个人在玩游戏时说:
"啊, 马里奥死了", 或者是 "啊, 主人公死了" 之类的.

这是因为在游戏中, 玩家是一个沉浸参与的状态而不是一个类似于电影, 书籍之类的欣赏者状态.
(当然, 视觉轻小说之类的可能不太适用, 但是要我说, 视觉轻小说可能也能算得上文学 +bushi+).

一个比较好奇的地方是类似于底特律变人这样的可以说互动电影的游戏,
以及一些几乎没有角色扮演成分的 AVG 游戏 (比如丸子与银河龙),
是否会让人有参与感呢? 或者说, 玩家是否会映射部分的自我到一个特定的角色上,
去寻求一个代入感呢? 

这个用户体验, 在 [[#mda][MDA]] 的设计框架里面, 应该算是美感 (Aesthetic) 的部分.
#+begin_html
</details>
#+end_html

* 如何开始游戏设计
** 从体验开始设计
如上, 游戏的体验是游戏设计的关键, 所以在设计的时候应当着重表达这种体验.
这个时候, 游戏就像是一个个人的表达: 因为想要做有这种体验的游戏, 所以做这样的游戏.

#+begin_html
<details><summary id="mda">MDA</summary>
#+end_html

可以去读一读 [[https://www.bilibili.com/read/cv19232898/][MDA 框架：一种游戏设计和游戏研究的形式化方法 (2004)]],
是一种分析和构思游戏设计机制的一个模型框架. 其代表了:
+ 机制 (Mechanic) 
+ 动态 (Dynamic)
+ 美感 (Aesthetic)

以下是我的一个简单的概括 (不一定对):

这三个类似于一个逐级放大的效果, 开发者设置了自己的机制, 通过动态来调整游戏的平衡性,
反应在玩家层面的便是一种美感的体现.

当然, 并没有那么简单, 这几个词也不仅仅只是简单的字面意思, 建议还是去读读看翻译的原文.
但是因为我做得还比较少, 所以可能不太能够很好地表述和理解.
#+begin_html
</details>
#+end_html

** 从玩家到开发者
从体验游戏到构思游戏之间有一个比较 "巨大的鸿沟",
就是并不是所有的玩家都愿意去做开发者, (估计还有一个反向鸿沟是开发者可能不全是玩家,
不过这个估计在未来不太可能).

一个误会可能是因为游戏形式: 好像大家认知里面的游戏都是类似于电子游戏,
比如王者荣耀这样的 moba, 传奇这样的页游, 原神这样的主打二次元花钱养老婆的游戏等等.
那么想要开发电子游戏我们需要什么? 编程. 好的, 那么这就刷掉一波可能有些想法,
但是仅仅可能只是停留在想法层面上的人了.

但是实际上游戏的形式是多种多样的, 扑克, 麻将, 大富翁 (以及其他可能的 "桌游"),
(以及其他可能的游戏形式, 太多了). 想要设计一个游戏其实并不一定需要很多很复杂的技术,
纸笔小游戏就足够构建一个比较有趣的小游戏了.

#+begin_html
<details><summary>这就像是看论文</summary>
#+end_html
怎么变成这样的一个话题了呢? 因为在看论文的时候,
一般都会比较在意论文里面为什么要这么做. 关键是为什么.

当然, 也许只是因为我只是一个臭搞实验的, 现在看的都是一些别人是怎么做实验的论文,
(搞理论的大佬如何想就不清楚了). 但是了解了为什么, 就会在新的实验设计里面去尝试去复刻,
或者说想想如何利用这种 "为什么" 去设计新的实验之类的.

(当然, 照着抄肯定是不可能的, 就像我导师之前很自豪地说过, 公式都是公开的,
就算照着抄也不可能的, 因为每个探测器都是不一样的)

好好好, 还是回到游戏. 
#+begin_html
</details>
#+end_html

** +暴政+ 保持个人的特色
两个代表: 以日本开发者为代表的明星制作人的企画, 以及以欧美开发者为代表的 "合作".

(注: 表述可能不太准确)

相比欧美开发者的比较开放交流的合作模式:
比如在 GDC 展会上通过汇报交流来吸引更多的开发者加入; 
日本的游戏公司更像是一种比较封闭的一个公司自成一体的感觉.

你可能并不会看到宫本茂和宫崎英高在交流之类的,
但是你会发现每个人的作品都会有这个人负责的一个强烈的风格.
比如在塞尔达之前的里面的由钓鱼佬 (忘了叫啥了, 之前看纪录片的时候觉得这个很喜感)
加入的钓鱼元素之类的, 由或者是宫崎英高和魂类型游戏等等.

这种由一个人拥有一票否决权的有点类似于独断暴政的方法,
在某种程度上来说可以保持个人的特色不会因为类似于所谓的 "头脑风暴" 而消失.
其他人都是在帮忙为了实现这个最终的用户体验的这个特色而围绕在一起的.
这样的一个好处就是非常有其个人的特色, 保护了对应受众的一个用户体验.

#+begin_html
<details><summary>同人游戏, 开源游戏和 MOD 之类的</summary>
#+end_html
我认为同人游戏, 开源游戏和 MOD 开发之类的和这种保持个人特色的原则并不违背.
因为这并非像是一些大厂为了满足多数人的喜好而对作品在设计上加入的各种要素缝合.

这更像是个人为了能够表达自己的特色而去对游戏进行的一个修改, 致敬一样的感觉.
同人游戏, 比如东方 Project 更像是在已经有的世界观和人设基础上进行的一个自我发挥,
比如夜雀食堂之类的, 和原作基本上可以说玩法完全不同, 甚至美术和资源之类的都不尽相同.
(zun 绘估计是给了很多美工自信, 而 zun 曲估计给了很多人学习的案例吧).

并且很多游戏开发者都是从同人游戏或者 MOD 制作开始的, 可能除了热爱这个游戏,
想要为这个游戏添加一些自己的特色之外, 这种开发可能也算是一种游戏开发简单的入门吧.
#+begin_html
</details>
#+end_html

** 好的设计是一个方案解决多个问题
一个例子是马里奥的水管设计: 它一下子就可以教会用户跳跃的操作.

(注: 我在 Switch 上试了试 FC 的马里奥,
最早教会用户进行跳跃操作的应该不能完全算是水管,
而应该是小怪物和感叹号方块. 不过这两个差不多, 所以就不必如此计较了).

这样的一个好处就是在提示用户如何游玩这个游戏的同时 (老任经典的新手教学),
也给玩家带来一个正反馈: 按下跳跃键, 呜呼, 你跳起来了, 并且你完全不需要考虑什么阻力,
一切都很自然, 然后在这个自然的过程里面, 你解决了这个问题, 所以你会得到快乐,
于是你会继续被这个游戏所吸引.

并且在最近的马里奥惊奇里面, 这种既是引导也是游玩乐趣的设计 --
比如那朵 "雄蕊痒痒的" 小花, 我去, 谁会不喜欢一个讲骚话的 NPC 呢?

另一个例子是瓦里奥制造: 如何让用户在短短数秒里面就 get 到这个小游戏的玩法?
如何设置这个提示? 如何使得这个提示能够不仅对新手友好: 你一下子就能够上手;
同时也不会给你一种一直在玩新手教程的无聊感觉? 这就像是小孩子的游戏,
你完全不需要什么复杂的游戏机制 -- 比如抓人游戏, 这光听名字就能够理解这是啥,
并且在这个简单的机制里面, 你还能玩得很开心, 还能够一遍遍地去玩这个游戏.

+ 首先是需要一个简单的机制的表现手法. 也许你可能是有一个非常复杂的机制,
  但是不论如何, 都应该需要有一个简单的, 容易理解的入口.
+ 其次是需要一个变化, 你需要让这个简单的机制能够进行一个演化.
  这个演化的过程不能够说就像是原本出现敌人的概率是 20 %,
  结果在 Boss 关卡出现敌人的概率变成 100 % 甚至更高.
  这样就没有意思了 (失去了平衡性).

  在瓦里奥制造里面, 虽然也有类似这样的做法: 比如更快的速度, 更小的命中区间,
  但是除了这些, 还有略微丰富游戏机制: 从简单的吃钻石变成过障吃钻石,
  这种是在原本机制上的一些简单拓展. (就像是在抓人游戏里面的不同地区的小小演化).
+ 注: 你可能会发现上面两个有点对应 MDA 里面的 (Mechanic 和 Dynamic) 两部分.

* 独立游戏的未来
** 独立游戏开发者
实际上现在随着技术的普及, 开发者的数量应当会越来越多 -- 实际上,
会计算机的人越来越多了. 比如可以看到来自巴西的开发团队 (这就像是以前,
在 GDC 上看到来自中国的开发队伍).

但是另外一方面, 一些游戏开发的框架, 游戏设计的技术也越来越成熟,
这些成熟的框架虽然 (大大) 简化了开发流程, 但是也同时引入了一些专业术语,
容易让人不敢进入. (感觉可能需要未来有更多类似于做游戏的游戏来引导更多的非开发者,
来进入这个游戏开发的一个世界).

另外一个比较现实的问题就是, 独立游戏开发者可能大多都是一个规模较小的团队,
这也意味着其人均利润率还算是一个比较高的职业 (bushi). 并且对于开发者来说,
独立游戏的开发者往往拥有更加全面的游戏设计流程 (尤其是游戏设计部分) 的经验,
相比其他的一般螺丝钉更加不具有可替换性.

** 游戏形式的转变
在只有大厂才做游戏的过去, 或者说, 大多数用户的常见偏见中, 大概只有那种大厂之作.
但是大厂的游戏往往因为为了赚钱走的是量大管饱的路线, 忽视了游戏的体验 (玩法),
并且因为缺乏特色而难以形成有所影响力的游戏 -- 尽管可能可以一时赚到钱,
但是可能没法有很多好的积累.

类似米哈游这样只做二次元的在一个赛道上开花的也不是不行,
但是可能还是难以形成一个百花齐放的环境. 当然, 你要说政策不支持,
那当我没说. 尽管现在的玩家不多, 但是现在的大学生 (或者说年轻群体)
对游戏的接触和需求实际上是在逐渐扩大的 -- 而这些群体才是未来游戏市场的一个消费主力.

所以作为更加注重玩法的独立游戏, 其在吸引对应群体, 并且由于独立游戏的开发,
其本身还是比较具有多样性的.

** 独立游戏发行商是如何选择游戏的
大佬作为独立游戏发行商的身份和我说, 一般独立游戏会有几个负责人,
每个负责人都有自己不同的喜好, 当一个负责人想要去发行一个游戏时,
一定是要自己完全玩过这个游戏, 并且认为这个游戏很吸引自己 -- 或者说,
能够吸引自己代表的一类玩家.

简而言之, 和传统的游戏发行不同, 独立游戏需要更加注重用户体验 -- 毕竟是个人的表达.

* 游戏的设计
这里提出一些在实际游戏中的一些比较有趣的设计, 但是因为写这段文字的时候,
已经是过了好久了, 我不敢保证我的脑子里还剩下啥.

** 个人的表达
比如在合金弹头里面, 你可能会看到在战场上的小婴儿, 人被打后变成大肉棒,
或者是被木乃伊的毒气变成木乃伊 -- 然后你甚至还能够通过缩成一团绷带来蹲下...
这一切都有一种荒诞的搞笑的感觉, 这就是一种个人的表达.
你会因为这样的表达而感到很好玩, 这就足够了, 这就是一个你玩这个游戏的理由了.

** 失败惩罚和失败鼓励
游戏失败了肯定会有一个惩罚机制: 比如在常见的弹幕射击里面,
你死了之后就会回退到最初始的子弹配置.
但是往往又会有一些激励策略来鼓励你在失败后投币复活: 比如会在你死后爆几个增强道具,
或者是在你死后复活给你来一个大爆炸清屏.

* 其他
** 模拟器
假如有试过在 PSP 模拟器上玩歌姬计划, 或者试过在 NDS 模拟器上玩节奏天国的话,
估计可以理解软件模拟器的一个很狗的一个地方: 延迟.

(虽然经常吐槽的就是那帮臭打游戏的, 整天帧率帧率的, 但是在一些比如说音游上,
确实延迟还是很要命的)

于是现在有一个趋势就是用硬件去直接 "复刻", 或者说硬件模拟芯片 (FPGA 方案).
相比于软件模拟, 硬件的模拟的一个好处就是可以减少延迟以及解决音源的还原
(这个可能是一个比较新的地方).

(当然, 能搞到老机子肯定是更好的)

我尝试了一下大佬用硬件模拟的街机游戏博物馆, 只能说, 真爽啊!

** 日本的街机文化
不知道你有没有看过 《高分少女》 这部漫画 (也有改编动漫), 如果有,
那么你肯定能够从漫画里面看到这个作者对这个街机文化的一个强烈的爱.

+(题外话, 作者其他的作品可以暂时不必看看, 毕竟高分少女应该算是作者一众恐怖作品里面少数的欢乐向漫画了)+

在街机厅里面, 日本人可能会在排队的时候看着别人去玩这个游戏,
然后去观察别人的操作 (有点类似于我们现在看攻略视频), 然后学习别人的操作,
或者是根据自己的理解打出自己的新的操作, 这个时候, 可能原本在玩的人也会看到,
这样就逐渐积累了一个游戏的技术的交换氛围.

这有点像是在开源程序里面的程序的组织 -- 你从开源代码中学到了如何进行这个代码的表达,
同时, 别人可能也能够从你的代码里面学到新的东西. 

* 大佬何许人也?
大佬是独立之光VP, 纸上游戏工坊发起人熊拖泥 Tonyshong.
