#+layout: post
#+title: 光学 (期末)
#+date: 2023-1-4
#+options: _:nil ^:nil
#+math: true
#+categories: notes
* 常用结论
+ 简单的成像公式: $\frac{1}{u} + \frac{1}{v} = \frac{1}{f}$
  + 球面折射: $\frac{n_1}{u} + \frac{n_2}{v} = \frac{n_2 - n_1}{r}$
  + 球面反射: $\frac{1}{u} + \frac{2}{v} = -\frac{2}{r}$
  + 放大率: $M = \frac{v}{u}$
+ 分辨能力:
  已经知道光源或者接受光的物体的几何条件 $a$,
  判断能否分辨的最小区域 $>$ 半角宽即可. 
  + 对于狭缝的角宽度 $\frac{\lambda}{a}$ 以内的无法分辨. 
  + 对于圆孔的半角宽 $0.61 \frac{\lambda}{a}$ 的以内无法分辨.
    当然, 一般常用 $1.22 \frac{\lambda}{a}$.
+ 成像系统的匹配
  + 匹配的角放大率 $M_{eff} = \frac{\delta \theta_e}{\delta \theta_o} = \frac{D}{D_e}$,
    其中, $D$ 为主镜 (物镜) 的直径, $\delta \theta_e$ 一般为人眼 $= 3.4 \times 10^{-6} rad$.
    $\delta \theta_o$ 一般通过瑞利判据来计算. 

    类似的还有有效放大率 $M_{eff} = \frac{\delta y_e}{\delta y_m}$.
+ 光栅公式 $d \sin \theta_k = k \lambda$
  + 谱结构因子: $\alpha = \frac{\pi a \sin \theta}{\lambda}$
  + 谱形状因子: $\beta = \frac{\pi d \sin \theta}{\lambda}$
  + 角色散本领: $D_\theta = \frac{\delta \theta}{\delta \lambda} = \frac{k}{d \cos \theta_k}$
  + 色分辨本领: $R = \frac{\lambda}{\delta \lambda_m} = N k$
* 成像系统
此处的成像系统主要指的是几何光学中的成像系统.
且主要指的是单色光成像, 所以主要关心的是影响成像的几何因素,
如物像位置和焦距与光学系统本身的几何条件关系.

** 成像系统的基本分析理论
成像就是光从物点 $Q$ 经过光学系统汇聚到像点 $Q'$.
于是在这样的简单的想法下, 物平面上的一个点 $Q$ 可以通过:
计算光路来得到像平面上 $Q'$ 对应所在的位置. 
而假设有一个非常小的 $\delta Q$, 即 $Q + \delta Q \mapsto Q' + M \delta Q$,
于是就能够计算得到放大率 $M$. 

在计算光路的时候, 有 *逐次成像法* 和 *光线传递矩阵法*. 

*** 逐次成像法
思路就是把复杂光学系统分解成为简单的光学系统, 
然后对每个光学系统都进行逐次成像的计算. 

先从最基本的光学元件开始:

+ *球面反射*

  $$\frac{1}{u} + \frac{1}{v} = -\frac{1}{r/2}$$
  
  其中, 从光源发射方向看过去, 凸球面 $r$ 为正, 凸球面 $r$ 为负. 
  以及横向放大率:
  
  $$M = \frac{y'}{y} = - \frac{v}{u}$$

+ *球面折射*

  $$\frac{n_1}{u} + \frac{n_2}{v} = \frac{n_2 - n_1}{r}$$
  
  其中, 从光源看过去, 凸球面 $r$ 为正, 反之 $r$ 为负. 
  于是横向放大率为:
  
  $$M = \frac{y'}{y} = - \frac{n_1}{n_2}\frac{v}{u}$$
  
*** 光线传递矩阵法
将光线用: 

$$\left(\begin{array}{l}n\theta \\ x\end{array}\right)_{z}$$

来表示, 于是经过每个光学元件, 都相当于是乘上了一个变换矩阵. 
其中, $\theta y$ 为拉格朗日-亥姆霍兹不变量. 

+ 平移矩阵 $T(\frac{d}{n})$

  $$T = \left(\begin{array}{ll}1 & 0\\\\\frac{d}{n} & 1\end{array}\right)$$
  
  即:
  
  $$\left(\begin{array}{l}n\theta \\\ x\end{array}\right)_{z+d} = T\left(\begin{array}{l}n\theta \\\ x\end{array}\right)_{z}$$

+ 折射矩阵 $R(\frac{n_1 - n_2}{r})$

  $$R = \left(\begin{array}{ll}1 & \frac{n_1-n_2}{r}\\\ 0 & 1\end{array}\right)$$

+ 反射矩阵 $M = - \frac{2n}{r}$

  $$M = \left(\begin{array}{ll}1 & -\frac{2n}{r}\\\ 0 & 1\end{array}\right)$$

+ ABCD 矩阵  
  对于一般的结果, 也就是 $S = RTM$ 或者是这上面几个矩阵的乘积的组合. 
  这样的话, $S$ 应该有: $$S = \left(\begin{array}{ll}A & B\\\ C &D\end{array}\right)$$
  的形式. 并且因为 $\mathrm{det}(T) = \mathrm{det}(R) = \mathrm{det}(M) = 1$,
  所以 $\mathrm{det}(S) = 1$.
  
  于是只要研究 ABCD 矩阵即可知道光学系统的结论了:
  
  + $v = -\frac{D u + C}{B u + A}$
  + $M = \frac{1}{B u + A}$

** 波动光学对成像系统的影响
主要体现在对成像系统的匹配的影响上. 
** Examples
*** 薄透镜
薄透镜的组成就是两个球面折射:

$$L = \left(\begin{array}{ll}1 & \frac{n-n_0}{r_2}\\\ 0 & 1\end{array}\right)\
\left(\begin{array}{ll}1 & \frac{n_0-n}{r_1}\\\ 0 & 1\end{array}\right) =\
\left(\begin{array}{ll}1 & -\frac{1}{f}\\\ 0 & 1\end{array}\right)$$

于是可以计算得到焦距:

$$\frac{1}{f} = (n_0 - n)(\frac{1}{r_2} - \frac{1}{r_1})$$

下面是一些例题:
+ 单透镜位移法测量焦距

  屏到物距离 $l = 90cm$, 透镜移动 $d = 30cm$ 后重新成像.

  于是有方程:

  $$\left\{\begin{array}{lll}\frac{1}{u_1} + \frac{1}{l - u_1} & = & \frac{1}{f}\\\\\frac{1}{u_1 + d} + \frac{1}{l - u_1 - d} & = & \frac{1}{f}\end{array}\right.$$

  于是可以解得 $f$ 的值 $f = \frac{l^2 - d^2}{4l}$. 

+ 多透镜测量焦距

  透镜组成像, 保持物和屏距离不变, 第一次成像 $M_1 = -0.5$,
  透镜组向物移动 $d = 10cm$ 后, 仍成像.

  对于透镜组, 可以用物方焦距 $f_1$ 和像方焦距 $f_2$ 来描述.
  因为都在空气中, 所以 $f_1 = f_2 = f$.

  于是有方程:

  $$\left\{\begin{array}{lll}\frac{1}{u} + \frac{1}{v} & = & \frac{1}{f}\\\\\frac{1}{u - d} + \frac{1}{v + d} & = & \frac{1}{f}\\\M_1 & = & -\frac{v}{u}\end{array}\right.$$

  于是可以解得 $f = \frac{M_1 d}{M_1^2 - 1}$.
+ 计算物方焦距和像方焦距

  已知厚球面镜的前后球面半径为 $R_1$ 和 $R_2$. 中心厚度 $d$,
  材料折射率为 $n$, 物方折射率为 $n_1$, 像方折射率为 $n_2$.

  + 逐次成像法

    因为物方像距和像方像距都是对应着物方和像方的焦点,
    所以通过依次成像的方式应该可以计算得到. 

  + 转移矩阵法

    传递矩阵如下:

    $$S = R(\frac{n - n_2}{R_2}) T(\frac{d}{n}) R(\frac{n_1 - n}{R_1})$$

    于是可以有
    $S T(\frac{u_f}{n_1}) [n_1 \theta_1, 0] = [0, x_1]$,
    以及 $T(\frac{v_f}{n_2}) S [0, x_2] = [n_2 \theta_2, 0]$.
    其中 $x_1 = \theta_1 f_1$, $x_2 = -\theta_2 f_2$.

    最终应该可以计算得到 $f_0, f_1 = n_1 f_0, f_2 = n_2 f_0$
+ 已知一个透明介质球的半径为 $R$, 折射率为 $n$. 求主面位置.

*** 宽光束成像透镜
之前的结论都是建立在傍轴条件上的, 对于非傍轴条件并不一定成立. 
所以对于宽光束不适用, 可以使用光线微分方程来求解. 

*** 望远镜
+ 开普勒望远镜: 两个凸透镜 $f_o, f_e$ 成倒立的像.
  + 视角放大率: $M_T = -\frac{f_o}{f_e}$
+ 伽利略望远镜: 物镜凸透镜 $f_o$, 目镜凹透镜 $-f_e$, 筒长 $d$. 
  + 焦距 $F = \frac{f_o f_e}{f_o + f_e - d}$
  + $u_h = -\frac{f_o d}{f_o + f_e - d}$
  + $v_h = -\frac{f_e d}{f_o + f_e - d}$
+ 反射式望远镜

望远镜的 *角分辨本领*:

*** 显微镜
* 干涉系统
尽管在我看来, 一般的干涉系统的处理方法就是:
1. 确认是什么光之间相互发生干涉.
   在这个过程中, 基本就能够确认发生干涉的空间以及
2. 计算干涉的光程差 $\delta$
3. 计算干涉的强度, 以及其他的信息

以及干涉光学系统的一些概念, 因为干涉光学会涉及到光的波长,
所以在研究的时候需要对不同的光的波长进行考虑.
+ 色散本领: 能够将两个不同波长的光区分开来的本领.
  其影响的因素有瑞利班之类的. 

** 单次干涉
*** 分波前装置
将一束光的波前 (惠更斯定理) 分成两部分, 然后通过不同的路径产生光程差.
最终交汇在干涉成像面上.

+ 杨氏双缝

  通过双缝得到两个波. 
+ 费涅尔双面镜 (bimirrow)

  通过有一个小夹角的两片镜子的方式来将一个光源拓展成两个有张角差的光源.
+ 费涅尔双棱镜 (biprism)

  通过将一个棱镜切开变成两个竖直方向上有位移的两个光源.
+ 洛埃镜

  通过反射镜得到一个虚像, 虚像与原光源进行干涉.

*** 薄膜干涉
一束光在在薄膜表面分为两个部分:
+ 一部分反射
+ 一部分透射后反射再透射
  
根据成因不同, 有: 
+ 等倾干涉

+ 等厚干涉
  产生的光程差为 $\delta = 2 n h_p \cos r_p$.
  在小角度的时候, 可以忽略不计. 即 $\cos r_p \rightarrow 1$.

** 多光束干涉
类似于多个干涉光叠加的干涉结果:

$$A = \sum A_k e^{i\varphi_k} \Rightarrow \sum A e^{i k \delta}$$

常见的有法布里-珀罗干涉仪.

** Examples
*** 分波前干涉
+ 杨氏双孔的变种

  在基本的双孔实验基础上,
  + 在双孔和接受屏之间插入一块厚度为 $h$ 的折射率为 $n$,
    与接受屏平行的玻璃平板, 求间距 $\Delta x$.
    
    认为是两个经过玻璃透射成像的双孔在干涉.
    从屏看去, 两个光源的所在位置经过了两次成像:
    
    $$\frac{1}{u_1} + \frac{n}{v_1} = 0, M_1 = -\frac{v_1}{n u_1}$$
    $$\frac{n}{u_2} + \frac{1}{v_2} = 0, M_2 = -\frac{n v_2}{u_2}$$
  + 放一个焦距为 $F$ 的凸透镜. 使得双孔位于凸透镜的前焦面.

    认为经过透镜后为两个平面波之间的干涉.
    
    认为是两个经过玻璃透射成像的双孔在干涉.
    从屏看去, 两个光源的所在位置经过了两次成像:
    
    $$\frac{1}{u_1} + \frac{n}{v_1} = 0, M_1 = -\frac{v_1}{n u_1}$$
    $$\frac{n}{u_2} + \frac{1}{v_2} = 0, M_2 = -\frac{n v_2}{u_2}$$
  + 放一个焦距为 $F$ 的凸透镜. 使得双孔位于凸透镜的前焦面.

    认为经过透镜后为两个平面波之间的干涉.
    利用到透镜中心的光程相等的特点, 依次为等相位点,
    然后用来计算干涉场. 
+ 费涅尔双面镜

  *计算狭缝的极限宽度*

  实际上的极限宽度来自于干涉的像点能否辨别干涉的两个光源.
  这样理解, 对于一个干涉的像点来说, 就是距离它 $D$ 距离,
  有两个光源挨得挺近. 如果这两个光源太近了的话,
  那么就会被视为一个光源, 从而无法分辨.

  于是相干宽度就会被 $D$ 所限制, 即
  $d_0 = \frac{D \lambda}{b} < \frac{\lambda D}{2 \theta L}$

  于是可以计算得到结果. 
+ 劳埃镜

  *计算可以观察到的条纹数的上限* 

  观察到的条纹数就是可以发生干涉的空间长度 $L$ 除以 $\Delta x$,
  即 $N = \frac{L}{\Delta x}$.
+ 对切透镜

  *计算光源的极限宽度*

  可以计算一个前置问题: 当光源沿着拓展方向移动后,
  干涉条纹的移动情况 $\delta$. 然后只要移动的长度 $\delta < \Delta x$,
  即两个峰值不会重叠在一起, 就是光源的极限宽度了.

*** 薄膜干涉
+ 等厚干涉
  + 牛顿环

    在牛顿环中, 空气膜就是干涉的光程差的来源.
    于是 $\delta = 2 h = 2(\sqrt{R^2 - r^2} - R) \approx \frac{r^2}{R} = k \lambda$,
    于是有 $R = \frac{r_{k+m}^2 - r_k^2}{m \lambda}$.
  + 利用干涉的验平操作

    间隔 $\Delta x$ 的条纹, 计算倾角, 其实就是 $2 \Delta h = \lambda$,
    倾角 $\alpha = \frac{\Delta h}{\Delta x}$.
  + 增透膜

    让反射光相消即可. 令 $n_1$ 为空气折射率, $n_2$ 为玻璃折射率,
    取增透膜 $n = \sqrt{n_1 n_2}$, $h = \frac{\lambda}{4}$ 即可. 
+ 等倾干涉
  + 能够看到薄膜干涉条纹时, 人眼到薄膜相应位置的最小距离.

    实际上是两个问题的拼接, 一个是计算干涉条纹,
    一个是计算分辨本领.

    如果将问题更进一步: 考虑光源有一个宽度 $b = 5.0mm$,
    光源的波长 $\lambda = 589.3nm$, 光源到薄膜的距离 $l = 300mm$,
    入射角 $i = 30^\circ$, 薄膜厚度 $h = 80nm$, 折射率为 $n = 1.47$.
    人眼瞳孔直径 $d = 3.0mm$. 

    首先考虑光源的极限宽度: $b_0 = \frac{l \lambda}{2h \tan r \cos i} = 3.5mm$,
    发现 $b > b_0$, 于是需要人眼的限制. 即 $1.22 \frac{b_0}{l} \geq \frac{d}{S}$.

*** 多光束干涉
+ 法布里·珀罗干涉仪
  + 分辨波长在 $500nm$ 附近, $\delta \lambda = 10^{-4}nm$ 的两条谱线.

    即计算色分辨本领: $\frac{\lambda}{\delta \lambda} = m \pi \frac{\sqrt{R}}{1 - R}$, 
    于是可以得到 $m$, 然后 $m \lambda = 2 n h \cos \theta_m$.
  + 计算光源波长 $\lambda$

*** 偏振光干涉
实际上将偏振光分解成正交 (o, e 光) 的两部分就可以了.
然后可以利用公式:

$$I = A_o^2 + A_e^2 + 2 A_o A_e \cos \delta$$

其中 $\delta$ 为 o, e 光之间的相位差. 一般的操作:
1. 是否是自然光?
   如是, 自然光经过偏振片: $I \mapsto \frac{1}{2}I$,
   若否, 直接通过分解 o, e 光即可.
   不过需要注意的是圆偏振光, 因为会自带一个 o, e 相位差,
   在经过波晶片的时候要考虑相位差的正负关系.
   + 左旋: $\delta_{oe} = \delta_o - \delta_e = -\frac{\pi}{2}$
   + 右旋: $\delta_{oe} = \frac{\pi}{2}$
2. 经过偏振片: 马吕斯定理 $A \mapsto A \cos \theta$,
   其中 $\theta$ 为夹角.
3. 经过波晶片: 会产生相位差 $\delta_{oe}' = \delta_{oe} + \delta_B$.
   注意正负即可. ($\delta_B$ 为波晶片带来的相位差. )
* 衍射系统
实际上关心的就是光栅衍射. 一般的光栅,
即一个空间周期分布的东西, 一般的结果如下:

$$I(\theta) = i_0 (\frac{\sin \alpha}{\alpha})^2 (\frac{\sin N \beta}{\sin \beta})^2$$

通过谱结构因子和谱形状因子来描述一个衍射场的光强分布.
+ 谱结构因子, 其中 (以简单光栅为例): $\alpha = \frac{\pi a \sin \theta}{\lambda}$
  由单个狭缝 $a$ 宽度决定. 决定主极强的位置和半角宽度
+ 谱形状因子, 其中: $\beta = \frac{\pi d \sin \theta}{\lambda}$
  由 $d$ 为空间周期决定. 决定各个主极强的强度

** 理论分析
如果用农民的方式来做, 可以这样来处理:
+ 首先对每一个单元进行一次处理, 比如一个单元是一个单缝衍射,
  利用简单的衍射积分即可得到结论.
+ 然后对于周期性的整体, 通过无穷级数求和来得到最终的叠加效果.

*** 二维光栅
一个一维或者二维的光栅可以用透射分布来描述:

$$t(r) = t(\boldsymbol{r} + n \boldsymbol{d}_1 + m \boldsymbol{d}_2)$$

一个夫琅禾费衍射场可以描述为:

$$u'(\theta_1, \theta_2) = e^{-i k (x_0 \sin \theta_1 + y_0 \sin \theta_2)} u(\theta_1, \theta_2)$$

于是总光场即为所有单元的衍射场的叠加:

$$U(\theta_1, \theta_2) = \sum u'(\theta_1, \theta_2)$$

结论即为上文的公式.

+ 光栅公式: $\beta = k \pi \Rightarrow d \sin \theta_k = k \lambda$
+ 主极强的光强: $I(\theta_k) = N^2 i_0 (\frac{d}{k \pi a} \sin (\frac{k \pi a}{d}))^2$
+ 衍射场的暗点位置: $\beta = (k + \frac{p}{N})\pi, 0 < p < N \Rightarrow d \sin \theta_{k,p} = (k + p / N)\lambda$
+ 主极强半角宽: $\Delta \theta_k = \theta_{k + 1} - \theta_k$,
  $\Rightarrow d \cos \theta_k \Delta \theta_k = \frac{\lambda}{N}$.
  于是有 $\Delta \theta_k = \frac{\lambda}{D_k}, D_k = N d \cos \theta_k$.  

对于透射函数 $t$, 如果满足:

$$t = t_0 + t_1 \cos (p x + \varphi_0)$$

这样的形式, 那么就叫做正弦光栅. $p = \frac{2\pi}{d}$ 为光栅波矢,
$d$ 为空间周期. 平行光正入射到正弦光栅的出射场为:

$$u = A \mapsto u_1 = t_0 A + \frac{t_1 A}{2} (e^{i 2 \pi f x} + e^{-i 2 \pi f x})$$

出射光为三个不同方向的平行光: $k_{\pm 1x} = \pm 2 \pi f, \sin \theta_{\pm 1} = f \lambda$.

实际上就是因为乘上了一个透射函数的因子, 拥有了一个不同的相位而已.

*** 三维光栅
描述晶格点阵: 

$$\boldsymbol{R}_{hkl} = \boldsymbol{r}_0 + h \boldsymbol{a}_1 + k \boldsymbol{a}_2 + l \boldsymbol{a}_3$$

于是在衍射的过程中, 可以将入射光看作是经过一层一层的二维光栅衍射后的结果.

+ 布拉格条件:
  晶面: 晶格上三个不共线的点确定的平面.
  将晶格看作是等间距的平行晶面组成.
  有衍射条件: 
  
  $$2 d \sin \theta = k \lambda$$

  时, 满足衍射极强. 其中, $d$ 为晶面间距 (层高),
  $\sin \theta$ 为层与层之间位移对应的倾角.
  
** 光栅光谱仪
光栅公式:

$$d \sin \theta_k = k \lambda$$

影响一个光栅光谱仪的性能的指标:
+ 角色散本领: 即很小的波长变化, 是否能够被光谱仪在角度上分辨. 

  $$D_\theta = \frac{\delta \theta}{\delta \lambda} = \frac{k}{d \cos \theta_k}$$
+ 线色散本领: 实际上就是 $D_l = f D_\theta$,
  因为光谱仪通过一个透镜来聚焦到成像面上观察.
+ 色分辨本领:

  $$R = \frac{\lambda}{\delta \lambda_m}$$

  其中 $\delta \lambda_m$ 为最小可分辨波长. 通过 $D_\theta$ 来计算得到. 

  $$\delta \lambda_m = \frac{d \cos \theta_k}{k} \delta \theta$$

  而 $\delta \theta$ 可以通过锐利判据得到 $\delta \theta = \Delta \theta_k$.

  于是 $R = N k$ 仅与光栅序数有关.
+ 光栅的选择:
  + 由波长和可分辨波长差确定光栅周期和条数:

    $$k \lambda < d, N k = \lambda / \delta \lambda$$

  + 记录介质和光栅匹配:

    即与 $\lambda / R$ 波长变化对应的线移动等于记录介质的线分辨本领.

    $$\delta y = D_l \frac{\lambda}{R}, D_l = f D_\theta$$
+ 闪耀光栅:

  改写光栅公式为: 

  $$d (\sin \theta + \sin \theta_b) = k \lambda$$

  其中 $\theta_b$ 为光栅的闪耀角. 于是闪耀波长 $\theta = \theta_b$:

  $$\lambda_b = \frac{2 d \sin \theta_b}{k}$$
    
** Examples
+ 以波长 $\lambda$ 为光源的光栅 $\theta_1 = 17^\circ 8'$,
  用另外一个波长 $\lambda'$ 来做光源, $\theta_1' = 17^\circ 50'$.

  利用光栅公式: $d \sin \theta_1 = \lambda$.
  于是可以算得 $\frac{\lambda'}{\lambda} = \frac{\sin \theta_1'}{\sin \theta_1}$.
+ 光栅单色议中, 入射光波和接受方向夹角 $2 \theta_0$, 光栅常数 $d$,
  光栅法线方向和光波入射, 出射角平分线夹角 $\theta$, 光谱序 $k$.

  计算单色仪输出光波波长:

  实际上单色仪可以看作是一个闪耀光栅 (斜入射光栅公式):
  入射角 $\theta_i = \theta_0 + \theta$,
  衍射角 $\theta_d = \theta_0 - \theta$.
  于是有: 

  $$d (\sin \theta_d - \sin \theta_i) = k \lambda$$
+ 光栅常数 $d$, 缝宽 $a$, 波长 $\lambda$, 焦距 $F$.
  求夫琅禾费衍射场中衍射斑的数目 $N$:

  带入光栅公式: $d \sin \theta_k = k \lambda$.
  然后计算最远处的 $|k_m| \leq \frac{d}{\lambda}$.
  ($\sin \rightarrow 1$). 于是最多存在 $M = 2 |k_m| + 1$ 条衍射纹.

  然后检查是否缺级: 因为 $I = N^2 i_0 (\frac{\sin \alpha_k}{\alpha_k})^2$.

  $$\alpha_k = \frac{\pi a}{\lambda} \sin \theta_k = \frac{k \pi a}{d}$$

  减去这些缺级, 即可得到衍射斑的数量.
+ 折射率为 $n_1$ 和 $n_2$ 的介质被光栅常数 $d$ 的平面透射光栅分隔.
  计算 $\lambda$ 单色光以 $\theta$ 入射的 1 级衍射角.

  1 级衍射极强条件: 经过相邻单元的光程差为 $\lambda$:

  $$\Delta L = n_2 d \sin \theta_1 - n_1 d \sin \theta$$

  实际上和闪耀光栅类似.
+ 光栅为 $d/2$ 宽度, $d/2$ 间隔的, $h$ 高度凸起的光栅.

  实际上可以看成是:
  1. 两套黑白光栅叠加
  2. 单元衍射因子的改变
+ 光栅密度 $n = 600 /mm$, 1 级谱分辨波长 $600 nm$,
  $\delta \lambda = 0.05nm$, 计算有效宽度.

  实际上就是要计算 $N$ 而已. 因为色散本领 $R = N k = \frac{\lambda}{\delta \lambda}$.
+ 平行光入射费涅尔波带片, 已知波带片环数 $N$, 主焦距 $f_1$.
  计算焦点位置.
+ 二维光栅

  可以用布拉格公式

  三维光栅同理, 先搞定一个晶面, 然后进行计算.
+ 正弦光栅

  实际上操作流程如下:
  1. 计算透射函数 $t$
  2. 得到透射后的振幅分布: $u_2 = t u_1$

     一般的形式如下:

     $$u_2 = A(r) (t_0 + t_1 (e^{i k x} + e^{-i k x}))$$

     于是变成相位为三种的出射波. 类似双缝干涉可以计算出射角.
* 傅里叶光学基础
将空间分为前场 (照明空间), 衍射屏, 后场 (衍射空间), 以及接受屏.
一束光 $u_1$ 经过衍射屏相当于乘以一个透射函数 $t$,
变成在衍射空间传播的 $u_2$, 最终在接受屏成像.

引入一个光瞳的概念, $t = t_L$ iff 光瞳内 else 0:
+ 薄透镜的 $t_L = e^{i k n d_0} e^{-i k \frac{x^2 + y^2}{2F}}$.

  即, 任何透射函数中含有二次项的都可以等效为透镜.
+ 薄棱镜: 透射函数为相位调制函数 $t_P = e^{-ik(n-1)(\alpha_1 x + \alpha_2 y)}$

  即, 任何透射函数中含有一次项的都可以等效为棱镜. 
* Others
** 全息摄影
*** 基本原理
实际上感觉和干涉很像, 激光器提供光源,
*参考光* (照射到平板上再反射到全息片上)
和照射到物体上反射到全息片上的 *物光* 发生干涉.

在还原的时候, 通过激光器照射在全息片上产生实像和虚像.

*** 应用
+ 全息显微技术: 用显微镜观测样品的全息片
+ 全息干涉: 通过多次曝光, 再现不同时刻光场的干涉
+ 全息傅里叶变换: 通过发散的球面光作为参考光, 平面光波作为照明
  光波, 可以得到发散球面波中心所在平面光场的傅立叶变换.
+ 超声全息: 利用与光波波长相近的超声波, 产生等效的全息片,
  再采用光波再现.
+ 瞬态研究: 利用短脉沖激光拍摄全息照片, 记录系统的瞬时状态.
+ 防伪: 全息片无法复制.
+ 全息储存: 以全息片的形式记录二维信息方阵
** 光度学
*** 基本概念
同样光强, 不同波长的光在人眼中产生的明暗不同, 通过视见函数,
即光度函数 (luminosity functions) 来描述不同波长的光的明暗视觉效应.

*注: 是视觉效应, 所以主要是通过人的主观感受来判断标准的.*

+ 适光性 (photopic) 光度函数:

  $$V(\lambda) = \frac{I_0(555nm)}{I_0(\lambda)}$$

  明亮环境下, 人眼对绿光 ($555nm$) 最敏感, 所以用其来描述.
+ 适暗性 (scotopic) 光度函数

  显然, 这个是在昏暗环境下的感光能力.

  (昏暗环境, 对颜色并不敏感. )
+ 光通量:

  $$\Phi = K \int V(\lambda)I(\lambda) \mathrm{d}\lambda$$

  其中 $K = 683 lm/W$, 光通量单位为流明 (lm).

+ 发光强度: 光源沿某一方向的发光强度

  $$I = \frac{\mathrm{d} \Phi}{\mathrm{d}\Omega}$$

  单位为坎德拉 (cd)
+ 光源沿着某一方向的亮度 (luminance): 次方像单位投影面积的发光强度:

  $$B = \frac{\mathrm{d} I}{\mathrm{d} S^*} = \frac{1}{\cos \theta}\frac{\mathrm{d} I}{\mathrm{d} S}$$

  单位为尼特 ($1 nit = \frac{1 cd}{1 m^2}$).
  常用单位为熙提 ($sb = \frac{1 cd}{1 cm^2}$).
+ 被照明表面的照度 (iluminance): 单位被照明面积上的光通量

  $$E = \frac{\mathrm{d} \Phi}{\mathrm{d} S'}$$

  单位为勒克斯 ($1 lx = \frac{1 lm}{1 m^2}$).

*** 像的照度和主观亮度
+ 像的照度: 单位面积上像的光通量

  假设物为一个面积为 $\sigma$, 沿光轴亮度为 $B$,
  距离成像系统 $u$. 成像系统的孔径为 $D$,
  像方焦距为 $f$, 物方焦距 $F$,
  像距 $v$, 像的面积 $s$. 于是可以得到光通量:

  $$\Phi = \frac{k \pi D^2 \sigma B}{4u^2}$$

  其中, $k$ 为透光系数.

  $$\Rightarrow E = \frac{k \pi D^2 \sigma B}{4 s u^2}$$

  带入 $\frac{\sigma}{s} = \frac{1}{M^2}, M = -\frac{F}{f}\frac{v}{u}$,
  于是有:

  $$\Rightarrow E = \frac{k \pi D^2 B f^2}{4 v^2 F^2}$$

+ 主观亮度: 视网膜上像的亮度

  因为人只能看清视距以外的物体, 所以有:

  $$H = \frac{k \pi B}{4} (\frac{D_e}{F_e})^2$$

  其中, 瞳孔直径 $D_e$, 焦距 $F_e$ 可以发生变化.

  一般是使用光学仪器不会增加主观亮度, 但是如果光学仪器和人眼不匹配,
  反而会降低主观亮度. 
** 色度学
+ (光的) 三原色
  + 红光 $700 nm$ (红光末端)
  + 绿光 $546.1 nm$ (Hg 谱线)
  + 蓝光 $435.8 nm$ (Hg 谱线)
+ 三原色的相加减

  $$C = r R + g G + b B = w W - r' R - g' G - b' B$$

  即, 一个颜色的光 $C$ 可以看作是红 $R$ 绿 $G$ 蓝 $B$ 的混合,
  或者也可以看作是相减.

  认为白光 $W = \frac{1}{3} (R + G + B)$ 为等量混合三原色得到,
  故光通量之比: $\Phi_R : \Phi_G : \Phi_B = 1 : 4.5907 : 0.0601$.
  功率之比: $I_R : I_G : I_B = 72.0962 : 1.3791 : 1$.
+ 色匹配函数:

  混合三原色得到光谱色的定量函数
+ 色品图
+ 颜色和饱和度
+ 色分辨椭圆: 人眼能够分辨的波长变化约在 $1nm$ 左右
