#+title: 傻瓜 L 的奇幻漂流
#+date: 2023-09-04
#+layout: post
#+options: _:nil ^:nil
#+categories: misc
* 傻瓜 L 的奇幻漂流
** 序章
虫鸣声就像是海浪一般涌来, 远处的山坡在太阳的照射下本就有些朦胧,
在这滔滔的鸣叫声的冲击下, 仿佛也要向这边倒来, 倒来...

** 说起倒来
前阵子看见山上电锯声飘过来. 没错, 真的是看到,
就像是黑白漫画里面的那种拟声词飘在空中一样. 毕竟我带着耳机,
本来应该是听不见外面的声音的. 但是这个世界这么丰富多彩,
总归是有些文人才能使用的高级技术 -- 没错, 我猜当时我看见的那位,
呃, 虽然其隐秘于林荫之间, 裹藏身形于大衣之中, 使我不得见其真身,
当能够将那把武器使得飞快, 却只需要一小瓶汽油, 一台内燃机和一截传动机构,
想必也绝非等闲之辈. 绝不是光头强这种电视里的伐木工之类的搞笑角色,
大概是包租婆这样大隐隐于市的除草工吧 -- 毕竟这快刀割下杂草的声音,
被刀片 (其实也就是一根铁丝) 抛溅到坡下, 飘零到我的眼前.

这个飘零我觉得用得不是很好, 不过限于词穷, 我也没啥好进行修饰的词语,
实在不行, 还请您想想在海边堆沙子一样的体验吧. 海边的沙子在海水的浸泡下,
黝黑黝黑的, 沾满了水, 泥, 粘稠地扒拉在一起糊成一个小塔. 可是突然间,
太阳出现了. 暴怒的太阳将自己的光芒狠狠地砸在大地上,
黑色的沙子一下子发了光, 仿佛这沙子是白茫茫的雪, 天地一片白花花,
仿佛是在艳阳高照的 39 摄氏度的白雪皑皑的冬天. 水分被暖气片一样的太阳吸干了,
一下子, 沙塔被抽去了水的粘附, 失去了表面张力的塔一下子倒了下来,
沙拉拉, 沙拉拉... 就像是那些飘零的草叶一般, 沙子们沿着塔坡滑了下来;
山坡上的树, 草, 土沿着坡滑了下来, 就像是高高的海浪立在你的眼前, 倒下来,
倒下来, 倒下来...

但是海里的海草丛们并不在意这些, 它们密密麻麻地排列在红色绿色的岩石上,
海浪扑向它们的时候, 它们也不在意, 只是摇摆摇摆, 摆过去一浪又一浪.

头疼, 我被打飞了.

** 在海上漂流
沙 (上), 沙 (下), 沙 (上)... 水流拍击着我的身体, 四周是无垠的海水,
仿佛是落在了一个扭曲的世界里, 原初的海水生出它贪婪的舌头舔舐着头顶的太阳.
而太阳又愤怒地用它那高频的光剑将那不知廉耻的舌头击回到一个仿佛是水天相接处的地方.

我无声地看着这两位的打闹, 波浪平静地殃及我这条池鱼, 却也不温不火 --
哦, 顺带一提, 我这可不是在隐喻啥温水煮青蛙, 毕竟谁也不想说自己是只青蛙,
毕竟也没有公主来亲吻我, 所以与其暗讽自己是一只不会被公主亲吻的蛤蟆,
我觉得现在这个时候, 亲爱的读者不妨把我想象成一块破木板,
漂流在大海上更加合适一些.

说起破木板, 这个意象让我想到了 DC Watcher 里面的那个漫画中的漫画,
主角遭遇了海盗, 受了海难, 在漂流的过程中疯了, 最后虽然回了家,
但是杀了家人成为了自己害怕的海盗. 哦~ 真是块重口味的木板,
明明是块破木板...

啊, 不过没事, 本文是一个精神极其健康的小说 (大概), 应该不会有那么重口的发展吧.

是吧...

大概吧. 我还是飘在海上, 日子大概也是一天天的过. 太阳从头顶落到屁股下面,
又从腋下钻出冲到肚子上方, 在天旋地转而又毫无波澜的日子里, 我飘在海上.

好无聊啊.

** 发疯的三要素
首先大概是无聊吧.

叔本华说过, 人生就像是钟摆, (虽然我承认我确实挺摆的),
在痛苦和无聊之间来回摆动. 大概他是在说一种因为太忙于受苦而忽视了自己的无聊,
又或者是因为无聊而无暇受苦的痛苦吧.

可是我觉得这两者不过是女生的两个胃一样, 一个装着饱腹, 一个装着甜食,
两者都是嗷嗷待哺, 所谓的痛苦就不会无聊, 大概就像是吞下自己的手强撑着自己装着甜食的胃,
安慰自己说到: 没事的, 你已经受了足够多的苦了, 至少你就不会无聊了,
来, 吃吃自己的手吧, 忘记无聊吧, 感受痛苦吧. 至少确实不无聊了,
痛苦让我忘记了无聊, 而无聊也让我忘记了痛苦, 在来回摆动的回转中,
我还真不记得究竟是痛苦呢, 还是无聊呢, 还是什么呢.

大概是发疯吧.

在水面上仍然飘动, 波浪一遍遍地拍击着我的身侧, 衣衫被含有盐分的水侵噬,
却又被明亮的太阳烤干, 在表面结成一层淡淡的晶体,
灰黄又带有黑点的脏兮兮的盐的析出.

至少没有汗水的臭味, 啊, 不, 不, 不, 绝不是我平常的结果,
就是实验室里析出的那些精盐, 我也是小心翼翼地包在纸巾里从实验室里偷运出来,
然后被忘在裤兜里卷进洗衣机中...

啪, 洗衣机炸了, 透明的监视窗就像是潜水艇中的观察窗 -- 本应是这样的,
但是它炸了, 水流冲了出来, 把我冲到了这海上, 飘动... 啊, 无聊啊.

诶, 还要编剩下的两大要素, 据说中国古代都特别喜欢四大家,
是因为四个人比较适合坐在一起打麻将. 不过我觉得也很奇怪,
明明大家都说事不过三, 却又喜欢四大家, 是发 (八) 的一半,
还是胡得比较快呢?

算了, 本着摆就摆了的心态, 那么我就做如此声明: 剩下的两个就是无聊, 以及无聊.

无聊啊~

杀啊啊啊啊啊啊啊啊啊啊~

耳边响起来这样的话.

** 刺挠操
一堆鲤鱼冲了出来, 手里 -- 啊, 是鱼鳍上 -- 拿着一只只红通通的大虾,
从水里窜了出来, 大喊着冲向太阳, 在空中挥舞着大虾,
用虾虽熟透却仍有韧性的身体支撑着水面将自己弹射出去.

唔, 虽然很想吐槽这奇怪的轻功水上漂是怎么实现的, 但是这就是鲤鱼跃龙门吧.
想到这里, 我觉得倒是有一份惊奇, 倒是这份寡淡无味的无聊添了几分颜色.

可是这颜色一下子也消失了, 就像是放烟花一样, 鲤鱼们又落回了水中.
水面重新回到了不疼不痒的平静的波澜中.

** 平静的波澜
我从床上醒来, 摇摆摇摆, 天旋地转.
据说人的晕车和晕船是因为半规管意识到了和眼睛看见的不一样的冲突:
明明半规管被摇得花枝招颤, 但是眼睛却说, 嗨嗨嗨, 哪有的事儿. 
两个不同的信号开始打架, 大脑凭借着生物进化多年留下来的 "经验" 判断:
我怕不是中毒了? 毕竟病从口入, 所以直接狠狠地往肚子发送一个信号:
你小子别吃吃吃了, 快给我吐 (退) 吐 (退) 吐 (退)!

说罢, 它便一拳锤在我的肚子上, 砸穿了我的床板, 让我陷入了自由落体的窘境.
风钻过我的衣服, 吹起我的衣衫, 发出啪嗒啪嗒的声音, 身后传来这样的声音,
就像是沸腾的水在充满活力地冒泡.

对, 就像是一锅沸腾的水.

我掉到了一锅沸腾的水里面.

其实还好, 沸腾的时候, 液体里边大概是每个地方都在发生着剧烈的相变吧.
从液相变化到气相, 大概是这样吗? 可是万一如果是在高压, 高温, 低压, 低温,
或者是鬼知道什么条件下呢? You're now at no man's land. 这句话可不是乱说的.
我突然对自己的处境充满了好奇, 但是这份好奇在腹部的绞痛中不得不停了下来.

我的胃就像是被一只手死死捏住, 然后另一只手用力地往反方向搅动,
就像是不得不手洗衣服还指望着它能够快点晾干而决定在最后一次用伟大的人力脱水一般,
我的胃扭了起来, 然后...

呕~ 呕~ 呕~

世界都安静了下来. 眼前是西红柿炒鸡蛋.

好吧, 这也太恶心了, 还是不开玩笑了, 是我刚刚吃下去的西瓜和面包.
毕竟在这沙海之中, 长着的唯一植物就是面包树了, 而面包树壮硕的身躯上,
唯一能吃的就是它那类似于头皮屑一样掉落的面包了. 而至于西瓜,
不会吧, 还有人不知道, 西瓜是生长在海边的树上, 在暴风雨的召唤下坠落到海中,
然后通过洋流漂流到远方的海岸扎根进行生物入侵的一把好手吗?
不过能在海中泡了那么久, 也多亏了它们发展出的一套复合材料制成的外壳,
通过海绵构造储存空气, 利用内部的筋络抵御并吸收冲击,
使其能够快速排出空气并快速下潜, 躲避敌人的追击. 想要抓到它们,
没有一番眼疾手快, 估计就只能使用钱币枪射出的万恶资本主义供应链来捕获了. 

好吧, 确实很恶心, 不管讲什么样的故事都一样.

呕~ 呕~ 呕~

照理来说, 按照历史和人文的经验, 事情在第三次就应当停止.

呕~ 呕~ 呕~

呕~ 呕~ 呕~

好吧, 历史是过去的, 未来是不可知的, 至少现在, 我不是那么想吐了.

就是吐得有点饿了.

** 饿
但是在这个大沙漠里, 又有啥可以吃的呢?

还真的有.

她和我面面相觑, 不过我也不能这样草率地用 "她", 万一是他, 甚至是它呢?
毕竟啃食的时候, 为了防止尴尬, 我是从背后吃掉这颗头的.
这要是正面, 岂不是变成了恋尸癖的恶心舌吻?

不过说是从背后, 倒不如说是只有后一半,
毕竟是从沙漠里那个带冷气的售货架上取的早早被店员劈成两半的.
真要劈人, 估计是做不到的; 可是一旦变成了间接的劈人,
却变得仿佛只是自己掏掏腰包, 动动手指的事情, 甚至最大的担心,
却变成了自己的腰包, 有没有不小心被那乱挥的斧子给伤到.

突然间一激灵, 发现手里捧着的不是头颅而是个西瓜, 不禁大惊失色,
连忙摔在地上退避三舍, 这, 这, 这, 这可是个西瓜啊! 这怎么下得去口!

** 写到这里
诶, 写到这里就有点不太想写了, 这花里胡哨的文字, 可能毫无美感也全是语病.
充斥着一个正常神经病对不正常神经病的各种臆想和偏见,
满满的全是受英文和不恰当中文影响的过长而又没有什么实际意义的废话文学主导的超长的定语修饰语句.

所以就不写了吧. 好, 收笔.

* 后记
** 本文纯属虚构, 如有雷同
要不您还是去看看医生?
