#+title: 光合作用 - 天堂故事汇
#+date: 2024-03-06
#+layout: post
#+math: true
#+options: _:nil ^:nil
#+categories: stories-made-in-heaven
* About
偶尔也会想要写点虚构的小说故事, 比如给小孩子讲了一些睡前故事,
给朋友吹了一些牛皮, 事后想来自己这故事编的真是有趣,
于是就产生了把这些故事收集起来的想法. 美名其曰天堂故事汇,
毕竟故事汇里面的故事虽然不至于全是假的, 至少也是基于现实虚构的,
但是故事不就是这样的吗?

所以第一个故事就叫做 "光合作用".

* 光合作用
很久很久以前, 有一个伤心的小女孩. 啊, 你问我她为什么伤心? 哦, 这是因为那
一天她的爸爸给她买了她渴望了很久的一套百科全书,就是那种大概八九十年代的
那种纸张不是很好的, 颜色有些发黄的,甚至里面的内容现在看来也有一些粗糙的
百科全书. 嗯? 什么叫 "这不是应该开心吗? " 啊, 你先别急,故事的开头总会需
要有一些无伤大雅的谱垫的.

小女孩开心地看着看着百科全书, 她看到了世界上最小的胖鸟,世界上最爱运动的
胖猫, 以及世界上, 她认为的最幸福的生物 –衣藻 – 天哪, 怎么会有如此悠哉悠
哉的生物呢? 只需要晒晒太阳,就能够快乐地活下去. 于是她在 "衣藻" 这个美妙
的双音节单词之外,还记住了另外一个非常饶舌的, 却看起来非常高级的四字 "咒
语":光合作用. 她在心里想着, 嗯, 长大之后一定要通过光合作用,像衣藻那样悠
哉悠哉地活着.

可是现实是残酷的, 因为她的爸爸从图书馆倒闭淘来的这套百科全书,恰巧缺了那
么几本, 也就让她遗憾地无法从书上了解到这样一个残酷的现实:那就是人类没有
叶绿体, 是不能光合作用的. 不过她的爸爸妈妈倒不在乎这些,只是把这个叶绿体
当作是又一个圣诞老人的善意的谎言,骗她吃了好多以前不爱吃的绿色食品 – 哦,
忘了说了,这些绿色食品大多是从后院的野地里摘来的,之前她不爱吃的原因是因为
小时候和邻居家的野孩子一起常常往菜上尿尿. 现在她为了能够 "长叶绿体" 进行
光合作用, 甚至还和野孩子在关于: "尿或者不尿, 这是个重大的选择" 问题上起
了冲突,最终以磕掉颗乳牙, 但重踢了野孩子的裆部的优秀战绩取得了"禁尿法案"
的一致通过. 啊, 不过她不知道的是,野孩子把那一天记为了战败纪念日, 每到那
一天就会偷偷抓粑粑扔到她们家菜地里.

不过到了两个孩子最终都升上了初中, 这破烂事也终于得到了一个结束.

当然, 这破烂事的结束也不是什么因为年纪的成长而带来了阅历的增加,进而让人
更加成熟更加稳重, 要真是吃一堑长一智, 那么他俩估计早已博学古今了. 事情的
结束是小学临近结束的时候, 在科学课上那语文老师 – 没错,那时候哪来那么多科
学老师, 要不是他们得考初中了, 该上上课了,这位语文老师估计还是在忙着教三
年级以下的毛娃子们音乐课呢 –语文老师读了一遍课本, 而她则惊讶地看到了自己
熟悉的, 热爱的 "叶绿体". 好在老师非常的有原则, 哪怕是被她在课上质问了快
十多遍了,硬是不肯扭曲事实 – 人类是没有叶绿体的, 更别说什么光合作用了, 不
可能的!

现在你知道她为什么不开心了吧.

很遗憾, 生活就是这样, 平淡得让人发闷, 回到家她也没有啥为了真理报仇雪恨,
也没啥信仰崩塌世界毁灭, 该咋样还得咋样. 只是她, 有那么一些伤心罢了. 大概
这就是小孩子的长大吧. 渐渐的, 她对吃地里的菜也没那么抗拒了,野孩子见这也
没啥乐子了, 菜地大战这才终于随着他们升上了初中烟消云散了.

接下来的故事寡淡如水, 客官们若是觉得口渴, 大可自行抿一口,十八岁以下的我
推荐牛奶, 十八岁以上的也不推荐喝酒. 反正写到此时我已有些口干, 兼着又有些
尿急, 不妨搁下这小品文字,容我去趟水房, 一解人之三急, 一解口之干涸?

淦, 喝水被呛到了.

啊, 事情就是这么发展了下去, 就算不情不愿也无可奈何, 故事就是这样. 风平浪
静地. 咱们还是调点读者们爱听的故事, 潦草地记述往女孩的一生吧. 二三十的时
候, 小女孩和野孩子开始谈朋友了. 起因也没啥特别的,大概就是常常在一起的孽
缘吧. 啊, 不过虽然这么说,野孩子这个时候也还算是有了个人样, 虽然叫野孩子
有些不妥,但是我也没想好取个啥浑名.

两个人还算对付得过来, 毕竟小时候都是互扔粑粑的交情了. 两个人合力相互支撑
着对方, 和其他大部分的人一样买着房子,还着贷款, 为这柴米油盐, 苟活着日日
夜夜. 虽然不算啥艰苦岁月,也不能算是轻轻松松. 大概就是这种没啥风波的普通
日子.

直到野孩子把小女孩给绿了, 本来应该是就这样平平淡淡,但估计是涉事未深又或
是怎样, 出乎意料地,小女孩竟极度地伤心, 当天晚上就回了家, 在家门口的海边
上坐了一晚. 本来吧这里应该好好讲讲这故事的前因后果, 女孩是如何伤心的,可
是你现在要问我这些, 我却为那女孩有些内疚, 毕竟这般讲这故事,总有种消遣他
人的悲剧的戏谑意味. 可你要说这便是喜剧的底色,那我只好添点油, 加点醋了.

我们至今仍未清楚那晚她到底是如何地哭的, 毕竟哪怕是南方的海边,到了夜里也
总会有一丝丝的凉意. 究竟是不眠不休地哭的呢,还是半醒半睡地哭的呢, 我实在
是不清楚.

大概是悲伤了一夜, 唯有潮湿而又温暖的海风抚慰着她受伤的心灵,到了第二天早
上, 她竟萌生出跳海自尽的念头 – 真是何等的可怕, 尽管这野孩子是否真有那么
重要我也并不清楚,但大概是和光合作用这个梦想不太一样, 怕是不能轻易地放下,
可要是真的需要为之献上生命, 倒也不该如此的积极. 可是不论如何都要如此一了
百了吗, 此刻的她内心正在饱受煎熬,肾上腺素随着血管泵进了心脏, 心脏像是擂
鼓一般疯狂地锤动,她开始大口的吸气, 大口大口的空气被吸入了胸腔,她的眼前一
片模糊, 她的意识有些迷离, 海浪声就像是降采样的 Lofi,生命力就像是退去的潮
水.

可恰好村里的二傻晨跑路过边上 – 害, 请你不要质疑我是否在胡编乱造,二傻这人
不曾出现过的理由, 完全是因为他的爷爷奶奶把他养的太好,平时像个跟屁虫一样
跟着小女孩和野孩子, 但是因为小学三年级的时候被小女孩和野孩子作弄吃了只鼻
涕虫拉坏了肚子,从此在家里好生惯养地宠着, 毕竟虽然脑袋不太灵光,但是总归是
自己的宝贝孙子, 一来二去就这么和小女孩她们渐渐疏远了,则回完全是因为长大
了在家刷手机, 父母实在是看不下去,就抗议爷爷奶奶的娇宠把他定时轰出去走走,
所以说是晨跑倒也不能算对,毕竟摇摇晃晃四处乱逛也没啥运动量, 恰好晃悠到了
这海角旮旯.

二傻看见小女孩在这闹腾, 也不觉得奇怪, 只觉得这多了个傻子在叫嚷. 平日里父
母对自己的话恰好涌上脑子, 从嘴巴里蹦了出来: "你个二傻子,在这里闹腾啥呢!
". 可小女孩此刻神情恍惚, 哪里听得见这,仍然无动于衷地盯着海面, 大口吐息着
自己落水前最后的几口空气,

二傻哪里有被如此冷落, 便学着自己在电影里学到的那种帅气的动作,飞起一脚想
踢踢小女孩. 虽然二傻完全没想着用力,可小女孩还没等那穿着人字拖的脚丫子挨
上自己, 便跳了下去.

二傻哪里见过如此阵仗, 忙大喊: "不是我干的! ", 刚想着冲下去救人,却只看见
海水里汩汩地向外冒着气泡, 顿时吓得他愣在原地. 想起了多年以前小女孩和自己
说的光合作用: 氧气! 氧气! 她是在光合作用! 她在光合作用啦! 二傻大叫到.

虽然故事到这里是一个悲剧的故事,但是至少在她的生命的最后还算是实现了她小
时候光合作用的梦想,至少还算是残酷命运的最后一丝温柔吧. 至少我是这么想的.

什么? 什么叫做 "不要拿你的故事开玩笑了? ", 拜托啊,这个故事明明我觉得编的
挺好的, 不是很适合做睡前故事的吗? 你不过是在退潮的时候在海滩上摔了一跤,
差点没被不到小腿肚深的水淹死而已. 怎么叫做这就是你的故事了呢? 得亏我等在
你边上的时候想了这么久好故事,来安慰你竟然可以被淹死的羞耻感. 诶, 真是人
心不古.

* 后记
** 故事的种植
一开始这个故事大概就只是一个简短的对话, 大概类似于深夜发疯的故事吧:

#+begin_html
<details><summary>折叠了...</summary>
#+end_html

#+begin_example
A: 我为什么！
A: 不是衣藻啊啊啊啊啊啊
A: 我好像下辈子当衣藻啊啊啊啊啊啊
B: 闭嘴, 睡觉
B: 衣藻可没有视力, 四肢, 丰富的感官来用来摆烂
A: 我想要体验光合作用
A: 人类有什么类似的生理过程吗
B: 有的哦
A: 太好了
A: 你说
B: 首先你找一个人把你给绿了
B: 这个时候你很悲伤
A: 我感觉我的心态
B: 大口吸气
A: 。。。。
B: 这个时候吸收了很多的二氧化碳
B: 然后你决定一死百了
B: 于是跑去了海边打算投海
B: 天气还挺好的
B: 太阳有点猛烈
B: 在海边你却怂了
A: 氧气呢
B: 于是在烈日下面蹲着决定自己要不要自己真的去死
A: 产生的氧气在哪里
B: 这个过程中你就被太阳晒着
B: (别急, 光合作用才到光照这一步呢, 氧气还没合成
A: 哦
B: 然后因为太阳太猛了
A: 那你继续
B: 你觉得被晒的有点受不了
B: 隧打算停止回家先摆会儿烂, 改日再死
B: 但是这个时候
B: 好心的一般路过凉凉帮你推了下去
B: 你在海水中大口吐着气
B: 看啊
A: 。。。。。。。
B: 气泡从水里冒出来啦
A: 谢谢
B: 这珍贵的氧气
A: 我真的要笑了
B: 新鲜的很呢
...
B: 啊
B: 但是故事还有后文
B: 就是因为最近填海造陆
B: 其实你跳错了地方
B: 这海估计才到你小腿肚
A: 这么夸张
B: 所以一边被嘲笑一边被拍下了照片
B: 你成为了火遍全网的新热点 -- 人类历史上第一个光合作用的人!
B: 鼓掌, 啪啪啪~
B: 我敲你敲的啪啪啪
#+end_example

#+begin_html
</details>
#+end_html

但是就像是种土豆, 扔下去一个, 长出来好多, 于是最后就有了这个故事.
感觉挺有意思的. 
