#+title: 就像是在宁静的午后在阳光下悄悄地不为人知地升华
#+date: 2024-05-19
#+layout: post
#+math: true
#+options: _:nil ^:nil
#+categories: manga
* About
虽然取了这么个抽象名字, 但是实际上应该还算是一个比较积极向上的内容的 (吧).
我如是的想到, 不过实际上这是我看完了 水手服与机关枪 (1981, 药师丸博子的版本)
这部电影后的想法.

虽然是这么说, 但是倒不如说是找到了一个可以用来描述这句话的状态的电影.
有点像是船要沉没了, 然而却也没有什么改变, 静静地看着船一点点沉入水中.
但是这又和 奇诺之旅 (2017, 船之国) 的麻木不仁不同,
也和那种人定胜天的精神气不同, 大概就是一种 肖申克的救赎 中 "老布曾在此处",
既不是坦然接受, 又无力抗争, 却仍有所尊严的沉默不语的死亡.

不过也很难说, 毕竟千人千面, 没法很好地描述自己的感觉.
但是可以用来描述情感的东西倒是很少, 所以这个时候打算回过头来整理一下,
之前一大段时间看过的东西, 就当是打发这个升华的午后的时间吧.

* 水手服与机关枪 セーラー服と機関銃, 1981
#+begin_html
<iframe allow="autoplay *; encrypted-media *;" frameborder="0" height="150" style="width:100%;max-width:660px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.music.apple.com/cn/album/sailor-fukuto-kikanju/1653048120?i=1653048124&l=en-GB"></iframe>
#+end_html

在 b 站上瞎逛翻了一个 "预告片", 于是去找来了全部去看,
全片的节奏有一种不紧不慢, 钝刀割肉的感觉.

举几个例子:

彦 (Hiko) 骑摩托车那段, 霓虹灯光的光怪陆离, 声音的喧嚣, 分不清远近以及音调,
好像所有的声音都混在一起, 然后将人声单独地拉出来, 又仿佛很近,
摄像机抖得很厉害, 就像是醉酒的人在瞎拍, 仿佛就是在做梦.

然后梦就醒了, 彦 (Hiko) 就死了. 一个 "看似松了一口气然后就一棒子打死" 的经典情节,
但是处理得很不错, 那么是想要反转吗? 也并没有, 就像是被巨手碾压,
甚至练挣扎都是徒劳.

里面有这么一段话, 是这样的:

#+begin_quote
黑社会这玩意, 表面上神气活现的, 但内在早就腐烂变质了,
这种人一旦忍受不了自身发出的腐烂气味, 就会一头栽进更加肮脏更加腐烂的东西里,
生活在这种环境里我真想大叫发泄, 像狼那样纵声嚎叫!
#+end_quote

明 (Mei) 被警察刺伤那段, 我一开始还真的以为只是简单的刀伤, 在温柔的,
近乎奇迹一般的疗愈后, 故事就应当结束了. 然后就是开门, 一句 "你谁啊",
以及一阵枪声便草草了事的结局.

作为局外的旁观者, 我也只能是 "啊?" 的震惊, 然后就是电影中女主角 "寂静" 的反抗,
不是甘地的那种抽象的非暴力反抗, 而是蜉蝣撼大树的无力与无奈.
甚至最后只能是满面泪, 无力地晕过去, 又能改变什么呢?

不过其中的女主的人物形象确实是非常的坚强, 但是空有坚强又有什么用呢?
仍然是不成熟的弱小, 有着孩子一样的心理, 却被委以组长的身份.
想要成长却仍然是小孩, 哪怕是拿到了枪的力量, 也只能看着又一位 (政, Masa) 逝去.

不过要说唯一比较奇迹的估计就是竟然真的可以从中抽身吧. 不过真的抽身了么?
也没有吧, 佐久間 (Sakuma) 最后还是因为黑道而死. 嘛, 也确实, 因为
"这个人无法对黑道视而不见".

故事 (罗伯特·麦基) 一书中大概有说, 一个故事的进展大概是矛盾的进展,
矛盾逐渐激化达到高潮然后解决矛盾然后来到结局. 不过真的有所解决吗?
人在螺旋中上升, 矛盾依旧存在, 是不成熟的无力的 JK 对成熟和力量的冲突.

不过感觉这样的故事处理手法很难做到一个平衡, 比如往往一些烂番会让主角一直吃瘪,
然后调度读者的共情心理, 但是在最后又迫于读者对好结局的向往而让主角胜利.
而这部电影我感觉厉害的点就是虽然主角在吃瘪, 但是并没有特别的同情的共情,
(是女主角太坚强了么? ), 并且在最后也没有一般性的胜利, 却仍然有一种不强,
但是也不能说弱的安慰感. (尽管仍然是被这个最后的淡淡哀伤所混合,
不是一种简单的标签化的情感符号).

除了剧情, 大概还有的就是镜头和音乐吧.

里面的一些转场长镜头真的很厉害, 像我这种没见过世面的感觉很震撼.
然后音乐, (其实我觉得和 水手服与机关枪 这首歌比起来,
还是里面一直在清唱的那个 カスバの女 比较抓人耳朵,
不过让我觉得比较可惜的是, 貌似原曲是那种昭和的歌,
总有一种, 呃, 说得不好听点就是鼻子堵住的感觉,
没有电影里面清唱的那种高音的空灵感, 怎么说呢, 太有人味了,
没有电影里那种非人的, 有些神圣的那种感觉.). 

相比港片的那种近乎爽文的黑道故事, 这个电影对黑社会的态度几乎是完全的否定,
总归是悲剧, 不论怎么去艺术化加工, 都不可能脱离悲剧的结局. 

* 新宿事件, 2009
也是一个讲黑社会的故事, 或者说, 是背后一个并不是多么光辉的故事.
偷渡, 黑户, 外国人黑帮.

嘛, 虽然最后还是变成了窝里斗. 不过感觉和有人的地方就有江湖这个一样,
并不是因为什么万金油一样的什么劣根性这种搞笑的原因.

我觉得是因为一个个人身份认知错位的一个问题, 即 "这里不是家" 的外乡人情节,
加上 "没有家可回" 的 "被抛弃" 的身份认知导致的不可定居,
也不可回退的第一代移民者身上的矛盾.

在 "我住在这里的理由" 这个纪录片 ([[https://www.bilibili.com/bangumi/play/ep292684][bilibili]]) 里面,
里面也有采访过这个电影的顾问李小牧, 这个人怎么说呢, 不太能让人喜欢,
但是也不太好说太讨厌, 挺矛盾的一个人吧. 牛逼是真的牛逼, 厉害也真是厉害,
厉害在于其阅历的积累以及其应对的心态, 但是和后面的另外一个大佬 (久积三郎,
[[https://www.bilibili.com/bangumi/play/ep819862][bilibili]]) 相比, 我感觉李小牧的这个厉害有点像是一个厉害的痞子,
而后者 (久积三郎) 像是一种有文化的厉害人.

这两个我觉得可以基本上算是个互补了 (虽然可能有些不恰当,
毕竟李小牧并不是什么对日本非常有贡献的一个外国人吧, 但是差不多吧,
反正我也不是啥专业的), 但是两个人都会有一个因为外国人身份的困难,
因为外国人的身份而无法融入 (?)

以前我读林语堂的 中国人 的时候, 觉得很厉害的一个地方就是说犹太人的中国化,
即是一个中国文化的一个包容性. 民族的融合交流本就应当是一个理想的未来,
但是随着民族意识以一种奇怪的方式扩大, 这却让不同民族之间的接纳越来越困难了,
这真是遗憾啊.

而二代, 三代的移民者, 这个时候真的还是移民者吗? 是归化了呢? 还是算什么呢?
是否仍然需要背负自己的祖辈的身份的标签而收到区别对待呢? 我不清楚,
毕竟我也没有看到过合适的案例, 不过我倒很希望如果真的有类似李小牧这样的中国人,
在国外以政权者的身份去推动外国人和本国人的融合, 应该可以算是一种不错的实验,
其结果也应当会有所参考价值, 哪怕会是失败的. 

不过这么说来, 我又想到之前看到的一个新闻, 说的是美国的政治机构中有大批量的非裔,
或者说黑人, 从而在政治层面修改了黑人的地位. 虽然说不上算不算是反倒加剧了种族矛盾,
毕竟现在所谓的种族歧视还挺抽象的. 不知道这是否可能是一个外国人参政的方面例子.
不过其缺点我感觉有点不太好说明, 不过有一个反例感觉可以比较好说明我上面的缺点
[[https://www.bilibili.com/video/BV1Nr4y1F7Ee][もしも外国人参政権が実現したら (bilibili)]], 虽然有些抽象, 但是确实很抽象.
这位吉田一郎议员对外国人的参政的反对理由大概是:
一个是语言不通的问题, 外国人可以仗着外语直接进行一个加密策反的操作
(不过最牛逼的还是里面举的中国人的革命操作能力... ),

说回电影, 里面倒是有一个比较让我影响深刻的事情, 最后在下水道里的两不相欠的场景.
从下水道来, 从下水道去, 仿佛一生不过过街老鼠. 但是也有所希望,
至少在最后的一个场景里面, 来自不同民族的矛盾终于消解了. 

* 百元之恋, 2014
看之前还以为是一个完全的拳击运动题材的电影, 被先有的印象误导了.
(不过也没有看过热辣滚烫, 不评价, 不过确实是被奇怪的理由推荐看的这个电影).
其实感觉拳击完全只是次要的东西, 更多的篇幅还是 "百元" 这个属性吧,
大概就是廉价的无足轻重的人生. 

其实还是挺惨的, 里面问她为什么出场的音乐是百元店的 BGM,
回答是自己就只是价值百元的女人. 而最后也依旧是一个百元的女人,
再加上前面男人的失败, 以及失败后的颓废, 倒是让人也非常担忧.

卧槽, 我感觉自己已经被某些现实主义的该死的朋友影响的太多了,
首先想到的竟然不是因为拳击燃起了积极生活的斗志, 而是拳击失败,
大龄不可再赛, 正常工作没有, 还和一个拖油瓶男友, 这之后该怎么整.
不过在这里停止我觉得也挺好的, 如果讲了一个因此乐观向上,
生活平步青云的, 那也太过魔幻了; 而若是反转又回到失败,
那也有点太过绝望了.

不过最后的音乐确实很牛逼, 仿佛是被掐着脖子呻吟后的呐喊的悲哭.

* 垫底辣妹, 2015
总而言之, 虽然看完就觉得非常励志, 虽然故事非常的老套了,
大概就是好老师改变坏学生的故事. (虽然里面的 "坏学生" 真的能称得上坏吗? )

虽然说确实有点理想, 但是毕竟是现实中就真的存在的东西,
以及后面在 "魔法" 消退, 真正面对机械的学习的过程的痛苦也是很真实的.

不过感觉也不能以偏概全 (开始叠甲), 这样的教学方法我觉得也不一定就可以推广,
比方说公众开放日给小朋友介绍东西, 本来想要寓教于乐, 结果被毫不留情地指责:
"叔叔/阿姨, 你能不能讲快一点, 好啰嗦啊... " (我靠,
我好不容易把知识点想了一个适合小孩子能理解的场景诶, 真是让人伤心. )

当然, 我希望未来的教育肯定是可以做到那么因材施教, 循循善诱的.
以及我可能适合去写欧美风格的那种教材, 就是那种闲话一大堆的乐子教科书,
而不是苏式的教材, 后者太严肃了可能不适合我.

* 都市猎人, 2024
还是看一些比较轻松的东西, 虽然感觉这个 都市猎人 的剧情有点不是很好,
虽然据说原作很好, 但是里面感觉没有那种质感, 比如镜头就有点太干净了的感觉,
或者说, 没有那种真实感, 有一种网剧的粗制滥造的感觉...

不过没看过漫画, 单从我看的经验上来说, 其实早期的日本 OVA 之类的制作,
其实也没有现在大家吹嘘的那么牛逼, 有些作品虽然绘制的技术非常的牛逼,
但是里面的剧情, 或者说剧情的刻画, 就有点比较单薄, 尬吹感觉也不太好.

* 蒸汽男孩, 2004
比如 蒸汽男孩, 虽然大友克洋之前的回忆三部曲我也不是很能看懂,
但是蒸汽男孩是故事简单, 可以看懂, 但是不该这么整的例子, (我觉得).

(尤其是最后片尾的那一串类似于后日谈的东西, 什么东西... )

不过单看正片我觉得还是不错的, 大概就是一个力量和规约的矛盾冲突.

* 我们都是超能力者, 2013, TV
但是相比 (都市猎人) 之下, 同样都是有些超能力的 "科幻" 要素的 我们都是超能力者,
里面的特效可以说是人神共愤的那种拉垮 (毕竟是午夜档的低成本吧).

但是相比之下就会非常的有趣, 可能是因为黄段子吧... 不过虽然如此,
倒是把人的食色性也描绘得非常真实, 就是因为变态, 就是因为平凡,
但是因为想要成为英雄的矛盾心理产生了一堆脑子不太正常的超能力者.

不过某种程度上来说有点类似于一种额外的变化了, 从希望自身获得能力,
来改变现状, 到希望获得超自然的超能力, 来改变现状,
虽然最终都无法改变现状 (能够改变的也自由非自然的异常). 

* 女子警察的逆袭, ハコヅメ〜交番女子の逆襲〜, 2021 TV, 2022 Anime
感觉是那种和 非自然死亡 一样的骗我去做 XXX 职业的那种职业番.

怎么没人来拍做科研呢, 做科研遇到的抽象事情还少么, 真是的.
比如为了跑上古仿真软件, 需要配置奇葩环境, 然后还需要一些奇妙的踩坑,
最后才理解, 凎, 这玩意只能在 MSYS32 MINGW64 上跑, 或者是凎,
这个数据结构书里面的示意图有问题, 之类的. 卧槽这超有意思的好不好.
或者再加上一些测信号测了几分钟, 一看读数道数全零, 再一看发现信号线断了,
最后把信号线给焊上去, 我觉得这能和那个鸽子巢的 debug 一样吹好久了.

* 萌菌物语
类似的还有萌菌物语, 骗我学生物是吧. 可惜现在不做 iGEM 了,
里面的一些东西真的感觉很有让人想学生物的冲动.

(不过据说后面的因为生物太多把汉化组劝退了... )

有道理, 今天刚和别人聊到 "寓教于乐" 的教材, 比如 [[https://www.helloruby.com/books][Hello Ruby]] 这个儿童绘本,
[[https://poignant.guide/][Poignant Guide to Ruby]] _why 的经典读物, [[http://landoflisp.com/][Land of Lisp]] 和 _why 的挺像,
但是会比较正经一点, 便实际一点的读物. 没准以后可以往这种方向编写教材,
毕竟漫画确实很容易让人接受 (某些死不读漫画的死宅除外, 动画不是全部啊).

* 爱丽丝与藏六, 2017
没什么不是一巴掌能够解决的. 不过这时候倒是很庆幸老爷子是一个正经人.
虽然我觉得还是有点问题的, 毕竟作为 "权威者" 的老爷子在指导的时候,
还是有点生硬, 或者说强迫性的. 而当立场转变, 不再是权威者时
(面对 米妮·C 时), 就有嘴遁的嫌疑. 不过好的处理是不会被嘴遁所忽悠,
而是被女仆所解救 (嘴遁有时候真的挺科幻的, 至少对于我这种社恐来说是的).

不过, 日常番, 卡哇伊就完事了. 在虚拟世界里面找什么现实性.

* 神是中学生, 2005
かみちゅ!

神番! 真神番. 就有一种悠哉悠哉的感觉, 让人心情非常平静. 

* 目隐都市的演绎者, 超自然 9 人组
这两个和在一起说吧, 主要是有点懒得写了.

说实话, 其实我只是觉得这类型的讲故事的方式非常帅, 有一种多线交织的混乱美.
毕竟正常的叙述, 仅仅只是线性叙述有点过于平淡, 并且现实中也并不一定是像闯关一样,
事件是一个一个跳出来解决的, 更像是一股脑涌过来, 然后就需要一起解决.

(绝不是在说我的 DDL 的问题. )

并且更加厉害的是, 这个叙述需要在复杂的同时还要做到不会乱,
如果乱的话就会感觉观感不是很好, 在排布上我觉得还是比较有水平的. 

* 后记
大概比较有记忆的就是这些了, 可能有些看了但是忘了, (那真是太亏了,
不过毕竟还是因为时间有点太久了嘛, 虽然还是很亏就是了). 
