require "opal"
require "opal-jquery"

desc "Build app to app/main.js"
task :build do
  builder = Opal::Builder.new
  builder.build("opal")
  builder.build("opal-jquery")
  builder.build("opal-parser")
  builder.build("./code/machine.rb")
  builder.build("./app/main.js.rb")

  File.write("app/main.js", builder.to_s)
end
task default: :build
