name: Testing the GitHub Pages publication

on:
  push:
    branches: main

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: Pull the Repo to vm
      uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.6' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: |
           bundle install
           bundle exec jekyll build
           touch _site/.nojekyll

    - name: Publish Builds to gh-pages
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SQUASH_HISTORY: true
