name: Testing the GitHub Pages publication

on:
  push:
    branches: main

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: Pull the Repo to vm
      uses: actions/checkout@v3

    - name: Initial Env
      run: |
           apt-get update
           apt-get install -y build-essential ruby ruby-dev python3
           gem install bundler jekyll
           bundle install

    - name: Build Blog in vm
      run: |
           jekyll build

    - name: Publish Builds to gh-pages
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
